/**
 * BDS language dictionaries.
 *
 * Keep brand terms intact across languages: "BDS", "Beyond Dream Scholars",
 * "Dream Beyond Dream", "Dream Attic" stay as-is.
 * Header nav labels (Search, Menu, Academics, Campus, etc.) are NOT translated
 * per product decision — those elements have no data-i18n attribute in HTML.
 */
window.BDS_LANGS = {

  en: {
    // Hero
    'hero.subtext': 'Each day, BDS students, faculty, staff, and alumni worldwide commit their skills, knowledge, and energy to advancing the public good and making a lasting impact on society.',

    // Hero CTA
    'cta.title_line1': 'Educating Global Leaders with',
    'cta.title_line2': 'Purpose, Excellence & Mindfulness',
    'cta.subtitle': 'Beyond Dream Scholars nurtures passionate learners who dream beyond themselves, combining rigorous academics with daily meditation and character development.',
    'cta.apply': 'Apply Now',
    'cta.calendar': 'View Academic Calendar',
    'cta.visit': 'Schedule a Visit',

    // Quick Facts
    'quick_facts.title': 'BDS by the Numbers',
    'quick_facts.subtitle': 'Excellence in education, measured by outcomes and dedication',
    'quick_facts.years.label': 'Years of Excellence',
    'quick_facts.years.desc': 'Since 2020',
    'quick_facts.ratio.label': 'Student-Teacher Ratio',
    'quick_facts.ratio.desc': 'Personalized attention for every student',
    'quick_facts.acceptance.label': 'University Acceptance',
    'quick_facts.acceptance.desc': 'Our graduates excel globally',
    'quick_facts.countries.label': 'Countries Represented',
    'quick_facts.countries.desc': 'A truly global community',

    // News
    'news.item1.title': 'A World Level International School BDS',
    'news.item1.desc': 'At BDS, we transcend traditional boundaries to provide a world-class education that prepares students to lead with excellence and integrity in an interconnected world.',
    'news.item2.title': 'Beyond Dream, Beyond Border - Germany',
    'news.item2.desc': 'BDS Germany: Bridging rigorous academic excellence with global opportunity. We empower students to transcend boundaries and turn dreams into reality.',
    'news.item3.title': 'BDS Summer Camp at Ongdalsam',
    'news.item3.desc': 'A transformative retreat where nature meets global vision. Empowering students to go Beyond Dreams through mindful growth and forest adventures.',
    'news.item4.title': 'BDS Official Introduction',
    'news.item4.desc': "Empowering students to realize 'Dreams Beyond Dreams'—where personal passion meets global contribution. We nurture leaders who find their purpose and expand it to serve the happiness of others.",

    // Philosophy
    'philosophy.title': 'Education Philosophy & Core Values',
    'philosophy.subtitle': 'BDS goes beyond academic instruction. We focus on cultivating inner growth, purpose, and global responsibility.',
    'philosophy.dream.title': 'Dream Beyond a Dream',
    'philosophy.dream.desc': 'We guide students not only to discover their dreams, but to expand them — so that their aspirations contribute to the happiness and well-being of others.',
    'philosophy.global.title': 'Global Citizenship',
    'philosophy.global.desc': 'English as a tool for meaningful global communication. We cultivate persuasive, confident global leaders who can thrive on the world stage.',
    'philosophy.meditation.title': 'Meditation & Inner Development',
    'philosophy.meditation.desc': 'Through daily meditation, students learn to reflect, regulate emotions, and strengthen their inner resilience in a peaceful natural environment.',

    // Curriculum
    'curriculum.title': 'Curriculum & Academic Programs',
    'curriculum.subtitle': 'BDS operates a structured curriculum designed to build international-level academic competence.',
    'curriculum.american.heading': 'American-Style Curriculum & English Immersion',
    'curriculum.intl.title': 'International Curriculum',
    'curriculum.intl.desc': 'Classes conducted in English by qualified teachers recognized in the U.S., U.K., Australia, and other countries.',
    'curriculum.student.title': 'Student-Centered Learning',
    'curriculum.student.desc': 'Socratic method, debate, and project-based learning foster critical thinking and self-directed growth.',
    'curriculum.divisions.title': 'Academic Divisions',
    'curriculum.divisions.desc': 'Elementary, Middle, and High School divisions offer age-appropriate curricula aligned with international standards.',
    'curriculum.enrichment.heading': 'After-School & Enrichment Programs',
    'curriculum.talent.title': 'Talent Discovery',
    'curriculum.talent.desc': "Dedicated sessions to explore each student's unique talents and strengths.",
    'curriculum.reading.title': 'Reading Culture',
    'curriculum.reading.desc': 'Evening reading programs cultivate wisdom and empathy through literature.',
    'curriculum.nature.title': 'Nature Learning',
    'curriculum.nature.desc': 'Outdoor learning experiences enhance observation, mindfulness, and appreciation of nature.',

    // Environment
    'environment.title': 'Educational Environment & Facilities',
    'environment.subtitle': 'BDS is located in a nature-friendly area, providing an ideal environment for both learning and well-being.',
    'environment.campus.title': 'Campus Environment',
    'environment.campus.desc': 'Modern classrooms, labs, and learning spaces equipped with the latest educational technology.',
    'environment.dorm.desc': 'Safe, comfortable residential facilities designed to foster community and personal growth.',
    'environment.dining.title': 'Dining Hall',
    'environment.dining.desc': 'Nutritious, organic meals prepared in a temple-style dining facility, supporting health and mindfulness.',
    'environment.library.title': 'Library & Resources',
    'environment.library.desc': 'Extensive collection of books and digital resources for deep learning and research.',
    'environment.wellness.title': 'Wellness Spaces',
    'environment.wellness.desc': 'Fresh organic meals and natural surroundings enhance mental clarity and emotional balance.',
    'environment.meditation.title': 'Meditation & Reflection Center',
    'environment.meditation.desc': 'Dedicated spaces for daily meditation, assemblies, and quiet reflection, designed to cultivate inner strength, emotional balance, and mindful leadership within a peaceful natural setting.',

    // Community
    'community.title': 'Community & Student Well-Being',
    'community.subtitle': 'At BDS, every student receives individualized attention and support.',
    'community.mentorship.title': 'Personalized Mentorship',
    'community.mentorship.desc': "Small class sizes (8-12 students) allow teachers to tailor instruction to each student's needs and learning style.",
    'community.respect.title': 'Culture of Respect',
    'community.respect.desc': 'We foster a supportive community where honesty, empathy, and cooperation are valued over competition.',
    'community.health.title': 'Holistic Health Care',
    'community.health.desc': 'Fresh organic meals support physical health. Clean air and natural surroundings enhance mental clarity.',

    // Creativity
    'creativity.title': 'Creativity & Physical Education',
    'creativity.subtitle': "BDS believes in unlocking each student's full potential beyond academics.",
    'creativity.artistic.title': 'Creative & Artistic Expression',
    'creativity.artistic.desc': 'Support for V-log production, filmmaking, content creation, painting, b-boying, music concerts, and other artistic pursuits.',
    'creativity.sports.title': 'Outdoor & Sports Programs',
    'creativity.sports.desc': 'Opportunities rarely found in typical schools, including rowing, indoor swimming, horseback riding, and golf.',
    'creativity.mentorship.title': 'Expert Mentorship',
    'creativity.mentorship.desc': 'Professionals from various fields (Master Group) provide hands-on guidance and inspiration.',
    'creativity.events.title': 'Student-Led Events',
    'creativity.events.desc': 'Students plan and lead performances and events, creating meaningful opportunities for ownership and leadership growth.',
    'creativity.performance.title': 'Performance & Stage Opportunities',
    'creativity.performance.desc': 'Students regularly showcase their talents through concerts, exhibitions, showcases, and public performances, building confidence, stage presence, and expressive power.',
    'creativity.fitness.title': 'Strength & Wellness Training',
    'creativity.fitness.desc': 'Structured fitness and conditioning programs develop physical endurance, discipline, and resilience, supporting both athletic performance and lifelong well-being.',

    // FAQ
    'faq.title': 'Frequently Asked Questions',
    'faq.subtitle': 'Find answers to common questions about BDS admissions, academics, and campus life',
    'faq.q1': 'What are the admission requirements for BDS?',
    'faq.a1.p1': 'BDS accepts students in grades 9-12 who demonstrate academic potential, curiosity, and a commitment to personal growth. The application process includes:',
    'faq.a1.li1': 'Completed application form with personal essay',
    'faq.a1.li2': 'Academic transcripts from previous schools',
    'faq.a1.li3': 'English proficiency test (TOEFL/IELTS for international students)',
    'faq.a1.li4': 'Two teacher recommendations',
    'faq.a1.li5': 'Interview with admissions committee',
    'faq.a1.p2': 'We evaluate each applicant holistically, considering not just grades but also character, motivation, and alignment with our educational philosophy.',
    'faq.q2': "What makes BDS's meditation program unique?",
    'faq.a2.p1': 'BDS is one of the few schools worldwide that integrates daily meditation into its curriculum. Every morning begins with a 20-30 minute guided meditation session designed to:',
    'faq.a2.li1': 'Develop focus and mental clarity for academic work',
    'faq.a2.li2': 'Build emotional resilience and stress management skills',
    'faq.a2.li3': 'Cultivate mindfulness and self-awareness',
    'faq.a2.li4': 'Foster inner peace and balanced decision-making',
    'faq.a2.p2': 'Students consistently report that meditation helps them manage college application stress, improve concentration, and maintain emotional balance—skills they carry into university and beyond.',
    'faq.q3': 'What is the "Dream Beyond a Dream" philosophy?',
    'faq.a3.p1': '"Dream Beyond a Dream" is BDS\'s core educational philosophy that challenges students to think beyond personal success. Instead of dreaming only for themselves, we encourage students to ask:',
    'faq.a3.li1': '"How can my dreams benefit others?"',
    'faq.a3.li2': '"What positive impact can I make on my community and the world?"',
    'faq.a3.li3': '"How can I use my talents to address global challenges?"',
    'faq.a3.p2': 'This philosophy shapes everything from our curriculum to our community service projects, creating graduates who are not just academically successful but also socially responsible global citizens.',
    'faq.q4': 'How does BDS prepare students for top universities?',
    'faq.a4.p1': 'BDS maintains a 100% university acceptance rate through comprehensive college preparation:',
    'faq.a4.li1_strong': 'Rigorous Academics:',
    'faq.a4.li1_text': ' AP courses, SAT/TOEFL preparation, and college-level writing',
    'faq.a4.li2_strong': 'Small Classes:',
    'faq.a4.li2_text': ' 8:1 student-teacher ratio ensures personalized guidance',
    'faq.a4.li3_strong': 'College Counseling:',
    'faq.a4.li3_text': ' Dedicated counselors assist with applications, essays, and interviews',
    'faq.a4.li4_strong': 'Extracurriculars:',
    'faq.a4.li4_text': ' Leadership opportunities, community service, and unique programs',
    'faq.a4.li5_strong': 'Global Perspective:',
    'faq.a4.li5_text': ' International student body prepares students for diverse campus environments',
    'faq.a4.p2': 'Our graduates have been accepted to Stanford, UC Berkeley, Yale, MIT, and leading universities in Korea, the UK, and beyond.',
    'faq.q5': 'What is campus life like at BDS?',
    'faq.a5.p1': 'BDS campus life balances rigorous academics with holistic personal development:',
    'faq.a5.li1_strong': 'Natural Setting:',
    'faq.a5.li1_text': " Located in Chungju's serene countryside, providing a peaceful learning environment",
    'faq.a5.li2_strong': 'Residential Community:',
    'faq.a5.li2_text': ' Dormitory living fosters independence and close friendships',
    'faq.a5.li3_strong': 'International Environment:',
    'faq.a5.li3_text': ' Students from 15+ countries create a truly global community',
    'faq.a5.li4_strong': 'Daily Schedule:',
    'faq.a5.li4_text': ' Morning meditation, academic classes, sports/arts, evening study, and community time',
    'faq.a5.li5_strong': 'Healthy Living:',
    'faq.a5.li5_text': ' Organic temple-style meals, outdoor activities, and wellness programs',
    'faq.a5.p2': 'Students describe BDS as a supportive family where they grow academically, emotionally, and spiritually.',
    'faq.q6': 'What are the tuition and financial aid options?',
    'faq.a6.p1': 'BDS offers comprehensive tuition packages and financial assistance:',
    'faq.a6.li1_strong': 'Tuition:',
    'faq.a6.li1_text': ' Covers academics, boarding, meals, and most activities',
    'faq.a6.li2_strong': 'Merit Scholarships:',
    'faq.a6.li2_text': ' Available for students with outstanding academic or leadership records',
    'faq.a6.li3_strong': 'Need-Based Aid:',
    'faq.a6.li3_text': ' Financial assistance for families demonstrating need',
    'faq.a6.li4_strong': 'Payment Plans:',
    'faq.a6.li4_text': ' Flexible payment options available',
    'faq.a6.p2': 'We believe exceptional education should be accessible. Please contact our admissions office at admin@bds-korea.org or +82-70-7525-5517 for detailed tuition information and to discuss financial aid options.',
    'faq.cta_text': 'Still have questions?',
    'faq.cta_button': 'Contact Admissions',

    // Contact form
    'form.title': 'Contact BDS Admissions',
    'form.subtitle': "We'd love to hear from you",
    'form.fullName': 'Full Name',
    'form.fullName_placeholder': 'Enter your full name',
    'form.email': 'Email Address',
    'form.email_placeholder': 'your.email@example.com',
    'form.phone': 'Phone Number',
    'form.phone_placeholder': '+82 10-1234-5678',
    'form.country': 'Country',
    'form.country_select': 'Select country',
    'form.country.kr': 'South Korea',
    'form.country.us': 'United States',
    'form.country.cn': 'China',
    'form.country.jp': 'Japan',
    'form.country.vn': 'Vietnam',
    'form.country.th': 'Thailand',
    'form.country.other': 'Other',
    'form.grade': 'Student Grade Level',
    'form.grade_select': 'Select grade level',
    'form.grade.9': 'Grade 9 (Freshman)',
    'form.grade.10': 'Grade 10 (Sophomore)',
    'form.grade.11': 'Grade 11 (Junior)',
    'form.grade.12': 'Grade 12 (Senior)',
    'form.grade.other': 'Other / Not applicable',
    'form.inquiry': 'Inquiry Type',
    'form.inquiry_select': 'Select inquiry type',
    'form.inquiry.admission': 'Admission Requirements',
    'form.inquiry.tour': 'Campus Tour Request',
    'form.inquiry.tuition': 'Tuition & Financial Aid',
    'form.inquiry.programs': 'Academic Programs',
    'form.inquiry.life': 'Campus Life',
    'form.inquiry.other': 'Other Questions',
    'form.message': 'Message',
    'form.message_placeholder': 'Please share your questions or comments...',
    'form.contact_method': 'Preferred Contact Method',
    'form.method.email': 'Email',
    'form.method.phone': 'Phone',
    'form.method.either': 'Either',
    'form.submit': 'Submit Inquiry',
    'form.sending': 'Sending...',

    // Success modal
    'success.title': 'Thank You for Contacting Us!',
    'success.message1_prefix': "We've received your inquiry and will respond within ",
    'success.message1_strong': '24 hours',
    'success.message1_suffix': '.',
    'success.message2': 'A confirmation email has been sent to:',
    'success.close': 'Close',

    // Footer
    'footer.admissions': 'Admissions',
    'footer.apply': 'Apply Now',
    'footer.requirements': 'Admission Requirements',
    'footer.tuition': 'Tuition & Financial Aid',
    'footer.about': 'About BDS',
    'footer.calendar': 'Academic Calendar',
    'footer.philosophy': 'Our Philosophy',
    'footer.campus_life': 'Campus Life',
    'footer.contact': 'Contact Us',
    'footer.location': 'Chungju, South Korea',
    'footer.social': 'Connect With Us',
    'footer.copyright': 'Copyright © 2020-2026 BDS (Beyond Dream Scholars). All rights reserved.',

    // Header notice
    'header.notice': 'BDS Academic Calendar & Key Highlights',

    // Language dropdown
    'lang.label': 'Language',
    'lang.en': 'English',
    'lang.ko': '한국어',
    'lang.ja': '日本語',
    'lang.de': 'Deutsch',

    // Academic Calendar page
    'calendar.back': 'Back to Home',
    'calendar.page_title': 'Academic Calendar 2025-2026',
    'calendar.page_subtitle': 'Academic Calendar | BDS Global Leadership Academy',
    'calendar.highlights': 'Key Highlights',
    'calendar.fall_strong': 'Fall Semester:',
    'calendar.fall_text': ' September 2025 - December 2025',
    'calendar.winter_strong': 'Winter Break:',
    'calendar.winter_text': ' December 2025 - January 2026',
    'calendar.spring_strong': 'Spring Semester:',
    'calendar.spring_text': ' February 2026 - June 2026',
    'calendar.summer_strong': 'Summer Programs:',
    'calendar.summer_text': ' July 2026 - August 2026',
    'calendar.events_strong': 'Special Events:',
    'calendar.events_text': ' Mock Tests, APAP, Winter Concert, Easter Egg Hunt, and more',
    'calendar.intl_strong': 'International Programs:',
    'calendar.intl_text': ' BDS Germany, Summer Sessions, Intensive SAT/TOEFL',

    // Ongdalsam campus page
    'ongdalsam.nav_label': 'Our Campus',
    'ongdalsam.card_eyebrow': 'Our Campus',
    'ongdalsam.card_title': 'A campus in the mountains',
    'ongdalsam.card_lead': 'Our campus is set at 800 meters, deep in a forested range. See where your child lives, learns, and grows each day.',
    'ongdalsam.card_cta': 'Explore Our Campus',
    'ongdalsam.hero.eyebrow': 'Our Campus · Ongdalsam',
    'ongdalsam.hero.title': 'Where Your Child Lives, Learns, and Grows',
    'ongdalsam.hero.lead': 'At 800 meters above sea level, deep in a forested mountain range, our campus is not a retreat students visit — it is where they live each day. A quiet, safe, intentional place designed for learning, reflection, and healthy growth.',
    'ongdalsam.intro.eyebrow': 'A Campus in the Mountains',
    'ongdalsam.intro.title': 'A place shaped by twenty-three years of intention',
    'ongdalsam.intro.lead': 'Our campus grew from a vision first set down in 2003 — to build a learning home where young minds can rest, focus, and reach further. What began as a dream is now the everyday setting of BDS: forest air, mountain stillness, and a rhythm that protects the conditions for real growth.',
    'ongdalsam.intro.stat1_num': '800 m',
    'ongdalsam.intro.stat1_label': 'Elevation above sea level — clean mountain air, cooler summers, and quiet surroundings',
    'ongdalsam.intro.stat2_num': '23 years',
    'ongdalsam.intro.stat2_label': 'Of continuous work to shape this place into a home for learning and inner growth',
    'ongdalsam.intro.stat3_num': '4 seasons',
    'ongdalsam.intro.stat3_label': 'Of active programming — every season offers its own way of learning and living',
    'ongdalsam.pillars.eyebrow': 'Four Foundations of Daily Life',
    'ongdalsam.pillars.title': 'How each day is built',
    'ongdalsam.pillars.lead': 'Students at BDS do not just attend classes — they live a structured day built on four foundations that support focused learning and steady personal growth.',
    'ongdalsam.pillar1.title': 'Rest',
    'ongdalsam.pillar1.desc': 'The day begins gently. Students arrive at calm surroundings and wind down from the speed of the outside world, so that real focus and real sleep are possible.',
    'ongdalsam.pillar2.title': 'Movement',
    'ongdalsam.pillar2.desc': 'Daily body practice — breathing, walking meditation, martial arts, and outdoor activity — keeps the body capable and the mind clear.',
    'ongdalsam.pillar3.title': 'Meditation',
    'ongdalsam.pillar3.desc': 'Guided meditation is a daily practice, not an occasional class. Students learn to focus, to notice their emotions, and to return to stillness before and after studying.',
    'ongdalsam.pillar4.title': 'Inward Practice',
    'ongdalsam.pillar4.desc': 'Reading, writing, quiet reflection, and honest conversation. These are treated as essential skills for university, work, and life — not extras.',
    'ongdalsam.day.eyebrow': 'A Day on Our Campus',
    'ongdalsam.day.title': 'The rhythm of a day at BDS',
    'ongdalsam.day.lead': 'A typical day moves from quiet beginnings into focused academic work and then back into reflection. Meals, movement, and silence are treated as parts of the education — not interruptions to it.',
    'ongdalsam.day.t1_label': 'Morning meditation',
    'ongdalsam.day.t1_desc': 'A gentle start — breath, posture, and focus before the day begins.',
    'ongdalsam.day.t2_label': 'Breakfast',
    'ongdalsam.day.t2_desc': 'Fresh, organic temple-style meals shared together in the dining hall.',
    'ongdalsam.day.t3_label': 'Academic classes',
    'ongdalsam.day.t3_desc': 'Small-group instruction in English — discussion, writing, science, and the arts.',
    'ongdalsam.day.t4_label': 'Lunch & forest walk',
    'ongdalsam.day.t4_desc': 'A midday reset — real food, real air, and time off the page.',
    'ongdalsam.day.t5_label': 'Electives & movement',
    'ongdalsam.day.t5_desc': 'Sports, arts, martial arts, and talent programs chosen by each student.',
    'ongdalsam.day.t6_label': 'Reading & reflection',
    'ongdalsam.day.t6_desc': 'Quiet time to read, write, and think before the evening.',
    'ongdalsam.day.t7_label': 'Dinner',
    'ongdalsam.day.t7_desc': 'A shared meal in the community — unhurried and plant-forward.',
    'ongdalsam.day.t8_label': 'Evening study & closing meditation',
    'ongdalsam.day.t8_desc': 'Focused study with mentors, followed by a short meditation to close the day.',
    'ongdalsam.themes.eyebrow': 'The Seven-Day Rhythm',
    'ongdalsam.themes.title': 'A theme for every day of the week',
    'ongdalsam.themes.lead': 'Each day of the week carries a guiding theme — a Chinese character with a long tradition of meaning. Together they shape a weekly rhythm that helps students move between study, movement, stillness, and community.',
    'ongdalsam.theme1.label': 'Uprightness',
    'ongdalsam.theme1.desc': 'Acting with honesty',
    'ongdalsam.theme2.label': 'Stillness',
    'ongdalsam.theme2.desc': 'Settling the mind',
    'ongdalsam.theme3.label': 'Movement',
    'ongdalsam.theme3.desc': 'Healthy action',
    'ongdalsam.theme4.label': 'Pausing',
    'ongdalsam.theme4.desc': 'Stopping to notice',
    'ongdalsam.theme5.label': 'Observation',
    'ongdalsam.theme5.desc': 'Seeing clearly',
    'ongdalsam.theme6.label': 'Harmony',
    'ongdalsam.theme6.desc': 'Living with others',
    'ongdalsam.theme7.label': 'Clarity',
    'ongdalsam.theme7.desc': 'A clean, clear mind',
    'ongdalsam.facilities.eyebrow': 'Where Students Live',
    'ongdalsam.facilities.title': 'Homes and spaces built for learning',
    'ongdalsam.facilities.lead': 'Every space on our campus has a purpose — to rest the body, to feed it well, to focus the mind, and to bring students together. Parents are welcome to visit and see each one in person.',
    'ongdalsam.facility1.title': 'Green Ondol House',
    'ongdalsam.facility1.desc': 'Traditional warm-floor residences — small, clean, and designed for real rest. Students sleep here in calm, safe rooms supervised by residential staff.',
    'ongdalsam.facility2.title': 'White Sky House',
    'ongdalsam.facility2.desc': 'Open, light-filled living spaces overlooking the forest. Reading, small conversations, and quiet recovery take place here every day.',
    'ongdalsam.facility3.title': 'Dining Hall',
    'ongdalsam.facility3.desc': 'Temple-style meals — fresh, seasonal, and mostly plant-based. Meals are shared slowly, together, as part of the daily practice.',
    'ongdalsam.facility4.title': 'Meditation Hall',
    'ongdalsam.facility4.desc': 'A quiet hall for morning meditation and evening closing practice. Students learn here what it means to settle the mind.',
    'ongdalsam.facility5.title': 'Library & Reading Rooms',
    'ongdalsam.facility5.desc': 'A collection of books in English, Korean, and other languages. Quiet, warm, with long hours for reading and research.',
    'ongdalsam.facility6.title': 'Forest Paths & Outdoor Spaces',
    'ongdalsam.facility6.desc': 'Walking trails, outdoor practice areas, and open ground for movement, sport, and seasonal events.',
    'ongdalsam.gallery.eyebrow': 'The Place',
    'ongdalsam.gallery.title': 'A look at our campus',
    'ongdalsam.gallery.lead': 'A small window into the setting where BDS students spend their days. Families are always welcome to visit and see it in person.',
    'ongdalsam.parents.eyebrow': 'For Parents',
    'ongdalsam.parents.title': 'What matters most, for families',
    'ongdalsam.parents.lead': 'Sending a child to a boarding campus is a meaningful decision. These are the things we believe matter most — and that we work on every day.',
    'ongdalsam.parent1.title': 'Safety and care',
    'ongdalsam.parent1.desc': "Residential staff live on campus. Rooms are supervised, health is monitored, and families are kept informed of their child's wellbeing.",
    'ongdalsam.parent2.title': 'Healthy daily life',
    'ongdalsam.parent2.desc': 'Fresh mountain air, temple-style meals, real sleep, and a balanced rhythm of study, movement, and rest.',
    'ongdalsam.parent3.title': 'Focused learning',
    'ongdalsam.parent3.desc': 'A campus away from urban distraction, small classes, and mentors who know each student by name.',
    'ongdalsam.parent4.title': 'Open to families',
    'ongdalsam.parent4.desc': 'Parents are invited to visit, to observe a day on campus, and to speak with teachers and residential staff directly.',
    'ongdalsam.cta.title': 'Come see our campus in person',
    'ongdalsam.cta.lead': 'The best way to understand BDS is to stand in the forest, share a meal, and watch a day unfold. We warmly invite families to visit and meet us.',
    'ongdalsam.cta.visit': 'Schedule a Visit',
    'ongdalsam.cta.contact': 'Contact Admissions'
  },

  ko: {
    'hero.subtext': '매일 전 세계의 BDS 학생, 교수진, 교직원, 동문들은 자신의 역량과 지식, 에너지를 공익을 위해 헌신하며 사회에 지속적인 영향을 만들어 갑니다.',

    'cta.title_line1': '목적과 탁월함, 그리고 마음챙김으로',
    'cta.title_line2': '글로벌 리더를 키웁니다',
    'cta.subtitle': 'Beyond Dream Scholars는 자신을 넘어 꿈꾸는 열정적인 학습자를 양성하며, 엄격한 학업과 매일의 명상, 인성 교육을 결합합니다.',
    'cta.apply': '지원하기',
    'cta.calendar': '학사 일정 보기',
    'cta.visit': '방문 예약',

    'quick_facts.title': '숫자로 보는 BDS',
    'quick_facts.subtitle': '성과와 헌신으로 측정되는 교육의 탁월함',
    'quick_facts.years.label': '탁월함의 연수',
    'quick_facts.years.desc': '2020년부터',
    'quick_facts.ratio.label': '학생-교사 비율',
    'quick_facts.ratio.desc': '모든 학생에게 맞춤형 관심',
    'quick_facts.acceptance.label': '대학 진학률',
    'quick_facts.acceptance.desc': '전 세계에서 활약하는 졸업생들',
    'quick_facts.countries.label': '참여 국가 수',
    'quick_facts.countries.desc': '진정한 글로벌 커뮤니티',

    'news.item1.title': '세계적 수준의 국제 학교 BDS',
    'news.item1.desc': 'BDS는 전통적인 경계를 넘어, 상호 연결된 세계에서 탁월함과 성실함으로 이끌 수 있는 학생을 길러내는 세계적 수준의 교육을 제공합니다.',
    'news.item2.title': 'Beyond Dream, Beyond Border - 독일',
    'news.item2.desc': 'BDS 독일: 엄격한 학문적 탁월함과 글로벌 기회를 잇습니다. 학생들이 한계를 넘어 꿈을 현실로 만들도록 돕습니다.',
    'news.item3.title': '옹달샘에서의 BDS 서머 캠프',
    'news.item3.desc': '자연과 글로벌 비전이 만나는 변화의 여정. 마음챙김 성장과 숲속 모험을 통해 학생들이 꿈을 넘어서도록 돕습니다.',
    'news.item4.title': 'BDS 공식 소개',
    'news.item4.desc': "학생들이 '꿈 너머의 꿈'—개인의 열정이 세계적 기여와 만나는 지점을 실현하도록 돕습니다. 자신의 사명을 찾아 타인의 행복을 위해 확장하는 리더를 길러냅니다.",

    'philosophy.title': '교육 철학과 핵심 가치',
    'philosophy.subtitle': 'BDS는 단순한 학업 교육을 넘어, 내면의 성장과 사명, 그리고 세계적 책임감을 기르는 데 중점을 둡니다.',
    'philosophy.dream.title': 'Dream Beyond a Dream',
    'philosophy.dream.desc': '학생들이 자신의 꿈을 발견하는 데 그치지 않고, 그 꿈이 타인의 행복과 안녕에 기여하도록 꿈을 확장해 나가도록 안내합니다.',
    'philosophy.global.title': '세계 시민 의식',
    'philosophy.global.desc': '의미 있는 글로벌 소통의 도구로서의 영어. 세계 무대에서 활약할 수 있는 설득력 있고 자신감 있는 글로벌 리더를 양성합니다.',
    'philosophy.meditation.title': '명상과 내면의 성장',
    'philosophy.meditation.desc': '매일의 명상을 통해 학생들은 평화로운 자연 환경 속에서 성찰하고, 감정을 조절하며, 내면의 회복 탄력성을 키웁니다.',

    'curriculum.title': '커리큘럼과 학업 프로그램',
    'curriculum.subtitle': 'BDS는 국제 수준의 학업 역량을 키우기 위해 체계적으로 설계된 커리큘럼을 운영합니다.',
    'curriculum.american.heading': '미국식 커리큘럼과 영어 몰입 교육',
    'curriculum.intl.title': '국제 커리큘럼',
    'curriculum.intl.desc': '미국, 영국, 호주 등에서 공인된 자격을 갖춘 교사들이 영어로 수업을 진행합니다.',
    'curriculum.student.title': '학생 중심 학습',
    'curriculum.student.desc': '소크라테스식 수업, 토론, 프로젝트 기반 학습이 비판적 사고와 자기주도적 성장을 촉진합니다.',
    'curriculum.divisions.title': '학부 구성',
    'curriculum.divisions.desc': '초·중·고등부로 구성되어, 국제 기준에 부합하는 연령별 맞춤 커리큘럼을 제공합니다.',
    'curriculum.enrichment.heading': '방과 후 및 심화 프로그램',
    'curriculum.talent.title': '재능 발견',
    'curriculum.talent.desc': '학생 개개인의 고유한 재능과 강점을 탐구하는 전용 세션을 운영합니다.',
    'curriculum.reading.title': '독서 문화',
    'curriculum.reading.desc': '저녁 독서 프로그램이 문학을 통해 지혜와 공감을 함양합니다.',
    'curriculum.nature.title': '자연 학습',
    'curriculum.nature.desc': '야외 학습 경험이 관찰력과 마음챙김, 자연에 대한 감수성을 높입니다.',

    'environment.title': '교육 환경과 시설',
    'environment.subtitle': 'BDS는 자연 친화적인 지역에 위치해, 학업과 웰빙 모두에 이상적인 환경을 제공합니다.',
    'environment.campus.title': '캠퍼스 환경',
    'environment.campus.desc': '최신 교육 기술을 갖춘 현대적인 교실, 실험실, 학습 공간을 운영합니다.',
    'environment.dorm.desc': '공동체와 개인의 성장을 돕는, 안전하고 편안한 기숙 시설입니다.',
    'environment.dining.title': '식당',
    'environment.dining.desc': '사찰식으로 준비되는 영양가 있는 유기농 식사가 건강과 마음챙김을 지원합니다.',
    'environment.library.title': '도서관과 자료실',
    'environment.library.desc': '깊이 있는 학습과 연구를 위한 방대한 장서와 디지털 자료를 제공합니다.',
    'environment.wellness.title': '웰니스 공간',
    'environment.wellness.desc': '신선한 유기농 식사와 자연 환경이 정신적 명료함과 정서적 균형을 높입니다.',
    'environment.meditation.title': '명상·성찰 센터',
    'environment.meditation.desc': '매일의 명상, 집회, 고요한 성찰을 위한 전용 공간으로, 평화로운 자연 속에서 내면의 힘과 정서적 균형, 마음챙김 리더십을 기르도록 설계되었습니다.',

    'community.title': '공동체와 학생 웰빙',
    'community.subtitle': 'BDS에서는 모든 학생이 개별 맞춤 관심과 지원을 받습니다.',
    'community.mentorship.title': '맞춤형 멘토십',
    'community.mentorship.desc': '8-12명의 소규모 학급으로, 교사가 학생 개개인의 필요와 학습 스타일에 맞춘 지도를 제공합니다.',
    'community.respect.title': '존중의 문화',
    'community.respect.desc': '경쟁보다 정직, 공감, 협력을 소중히 여기는 지원적인 공동체를 지향합니다.',
    'community.health.title': '통합적 건강 관리',
    'community.health.desc': '신선한 유기농 식사가 신체 건강을 돕고, 깨끗한 공기와 자연이 정신적 명료함을 높입니다.',

    'creativity.title': '창의성과 체육 교육',
    'creativity.subtitle': 'BDS는 학업을 넘어 학생 개개인의 잠재력을 온전히 꽃피우는 교육을 지향합니다.',
    'creativity.artistic.title': '창의적·예술적 표현',
    'creativity.artistic.desc': 'V-log 제작, 영상 제작, 콘텐츠 크리에이션, 회화, 비보잉, 음악 콘서트 등 다양한 예술 활동을 지원합니다.',
    'creativity.sports.title': '아웃도어·스포츠 프로그램',
    'creativity.sports.desc': '조정, 실내 수영, 승마, 골프 등 일반 학교에서 접하기 어려운 기회를 제공합니다.',
    'creativity.mentorship.title': '전문가 멘토십',
    'creativity.mentorship.desc': '다양한 분야의 전문가들(Master Group)이 실전 지도와 영감을 제공합니다.',
    'creativity.events.title': '학생 주도 행사',
    'creativity.events.desc': '학생들이 공연과 행사를 직접 기획하고 이끌며, 주인의식과 리더십 성장을 위한 의미 있는 기회를 만듭니다.',
    'creativity.performance.title': '공연과 무대 기회',
    'creativity.performance.desc': '학생들이 콘서트, 전시, 쇼케이스, 공개 공연을 통해 재능을 정기적으로 선보이며, 자신감과 무대 장악력, 표현력을 길러냅니다.',
    'creativity.fitness.title': '체력과 웰니스 트레이닝',
    'creativity.fitness.desc': '체계적인 피트니스·컨디셔닝 프로그램이 체력, 규율, 회복 탄력성을 길러 운동 수행과 평생의 웰빙을 지원합니다.',

    'faq.title': '자주 묻는 질문',
    'faq.subtitle': 'BDS 입학, 학업, 캠퍼스 생활에 대한 자주 묻는 질문들에 답해드립니다',
    'faq.q1': 'BDS 입학 요건은 무엇인가요?',
    'faq.a1.p1': 'BDS는 학업적 잠재력, 호기심, 개인적 성장에 대한 의지를 보여주는 9-12학년 학생을 모집합니다. 지원 절차는 다음과 같습니다:',
    'faq.a1.li1': '자기소개 에세이가 포함된 지원서 작성',
    'faq.a1.li2': '이전 학교의 학업 성적표',
    'faq.a1.li3': '영어 능력 시험 (해외 지원자: TOEFL/IELTS)',
    'faq.a1.li4': '교사 추천서 2부',
    'faq.a1.li5': '입학 사정 위원회와의 면접',
    'faq.a1.p2': '성적뿐 아니라 인성, 동기, 교육 철학과의 조화를 종합적으로 고려해 지원자 한 분 한 분을 평가합니다.',
    'faq.q2': 'BDS 명상 프로그램의 차별점은 무엇인가요?',
    'faq.a2.p1': 'BDS는 매일의 명상을 정규 커리큘럼에 포함한 세계에서도 드문 학교 중 하나입니다. 매일 아침 20-30분의 가이드 명상으로 시작하며, 다음과 같은 목적을 갖습니다:',
    'faq.a2.li1': '학업을 위한 집중력과 정신적 명료함 기르기',
    'faq.a2.li2': '정서적 회복 탄력성과 스트레스 관리 능력 함양',
    'faq.a2.li3': '마음챙김과 자기 인식 계발',
    'faq.a2.li4': '내면의 평화와 균형 잡힌 의사결정 능력 증진',
    'faq.a2.p2': '학생들은 명상이 대학 지원 스트레스 관리, 집중력 향상, 정서적 균형 유지에 도움이 되었다고 꾸준히 이야기하며, 이 역량은 대학 생활과 그 이후에도 이어집니다.',
    'faq.q3': '"Dream Beyond a Dream" 철학이란 무엇인가요?',
    'faq.a3.p1': '"Dream Beyond a Dream"은 학생들이 개인적 성공을 넘어서 사고하도록 이끄는 BDS의 핵심 교육 철학입니다. 학생들이 자신만을 위해 꿈꾸는 것이 아니라 이렇게 질문하도록 격려합니다:',
    'faq.a3.li1': '"나의 꿈이 어떻게 타인에게 도움이 될 수 있는가?"',
    'faq.a3.li2': '"나는 공동체와 세계에 어떤 긍정적 영향을 줄 수 있는가?"',
    'faq.a3.li3': '"나의 재능을 세계적 과제 해결에 어떻게 쓸 수 있는가?"',
    'faq.a3.p2': '이 철학은 커리큘럼부터 봉사 프로젝트까지 모든 영역을 관통하여, 학업적으로 뛰어날 뿐 아니라 사회적 책임을 갖춘 세계 시민으로서의 졸업생을 길러냅니다.',
    'faq.q4': 'BDS는 학생들의 명문 대학 진학을 어떻게 준비시키나요?',
    'faq.a4.p1': 'BDS는 종합적인 대학 준비 프로그램을 통해 100% 대학 진학률을 유지합니다:',
    'faq.a4.li1_strong': '엄격한 학업:',
    'faq.a4.li1_text': ' AP 과목, SAT/TOEFL 대비, 대학 수준의 작문 지도',
    'faq.a4.li2_strong': '소규모 학급:',
    'faq.a4.li2_text': ' 8:1 학생-교사 비율로 개별 맞춤 지도 보장',
    'faq.a4.li3_strong': '대학 진학 상담:',
    'faq.a4.li3_text': ' 전담 카운슬러가 지원서, 에세이, 면접을 지원',
    'faq.a4.li4_strong': '비교과 활동:',
    'faq.a4.li4_text': ' 리더십 기회, 사회봉사, 특별 프로그램 제공',
    'faq.a4.li5_strong': '글로벌 시야:',
    'faq.a4.li5_text': ' 다국적 학생 구성이 다양한 캠퍼스 환경에 대한 적응력을 키움',
    'faq.a4.p2': '본교 졸업생들은 Stanford, UC Berkeley, Yale, MIT를 비롯해 한국, 영국 등 세계 유수의 대학에 진학했습니다.',
    'faq.q5': 'BDS의 캠퍼스 생활은 어떤가요?',
    'faq.a5.p1': 'BDS 캠퍼스 생활은 엄격한 학업과 전인적 개인 성장을 균형 있게 추구합니다:',
    'faq.a5.li1_strong': '자연 환경:',
    'faq.a5.li1_text': ' 충주의 평온한 전원에 자리해 평화로운 학습 환경을 제공',
    'faq.a5.li2_strong': '기숙 공동체:',
    'faq.a5.li2_text': ' 기숙 생활을 통해 독립심과 깊은 우정을 기름',
    'faq.a5.li3_strong': '국제적 분위기:',
    'faq.a5.li3_text': ' 15개국 이상의 학생들이 모여 진정한 글로벌 공동체를 형성',
    'faq.a5.li4_strong': '일과:',
    'faq.a5.li4_text': ' 아침 명상, 정규 수업, 스포츠·예술, 저녁 자율 학습, 공동체 시간',
    'faq.a5.li5_strong': '건강한 생활:',
    'faq.a5.li5_text': ' 사찰식 유기농 식사, 야외 활동, 웰니스 프로그램',
    'faq.a5.p2': '학생들은 BDS를 학업적·정서적·영적으로 성장하는 따뜻한 가족 같은 공동체로 이야기합니다.',
    'faq.q6': '학비와 장학금은 어떻게 되나요?',
    'faq.a6.p1': 'BDS는 종합적인 학비 패키지와 재정 지원을 제공합니다:',
    'faq.a6.li1_strong': '학비:',
    'faq.a6.li1_text': ' 학업, 기숙, 식사, 대부분의 활동 비용을 포함',
    'faq.a6.li2_strong': '성적 장학금:',
    'faq.a6.li2_text': ' 학업 또는 리더십에서 두드러진 학생에게 제공',
    'faq.a6.li3_strong': '필요 기반 지원:',
    'faq.a6.li3_text': ' 재정적 필요가 있는 가정을 위한 지원 제도',
    'faq.a6.li4_strong': '납부 플랜:',
    'faq.a6.li4_text': ' 유연한 납부 방식 제공',
    'faq.a6.p2': '우수한 교육은 누구에게나 열려 있어야 한다고 믿습니다. 자세한 학비 안내와 재정 지원 상담은 admin@bds-korea.org 또는 +82-70-7525-5517로 문의해 주십시오.',
    'faq.cta_text': '더 궁금한 점이 있으신가요?',
    'faq.cta_button': '입학 문의',

    'form.title': 'BDS 입학처 문의',
    'form.subtitle': '여러분의 이야기를 기다립니다',
    'form.fullName': '성함',
    'form.fullName_placeholder': '성함을 입력해 주세요',
    'form.email': '이메일 주소',
    'form.email_placeholder': 'your.email@example.com',
    'form.phone': '전화번호',
    'form.phone_placeholder': '+82 10-1234-5678',
    'form.country': '국가',
    'form.country_select': '국가 선택',
    'form.country.kr': '대한민국',
    'form.country.us': '미국',
    'form.country.cn': '중국',
    'form.country.jp': '일본',
    'form.country.vn': '베트남',
    'form.country.th': '태국',
    'form.country.other': '기타',
    'form.grade': '학생 학년',
    'form.grade_select': '학년 선택',
    'form.grade.9': '9학년 (Freshman)',
    'form.grade.10': '10학년 (Sophomore)',
    'form.grade.11': '11학년 (Junior)',
    'form.grade.12': '12학년 (Senior)',
    'form.grade.other': '기타 / 해당 없음',
    'form.inquiry': '문의 유형',
    'form.inquiry_select': '문의 유형 선택',
    'form.inquiry.admission': '입학 요건',
    'form.inquiry.tour': '캠퍼스 투어 신청',
    'form.inquiry.tuition': '학비 및 재정 지원',
    'form.inquiry.programs': '학업 프로그램',
    'form.inquiry.life': '캠퍼스 생활',
    'form.inquiry.other': '기타 문의',
    'form.message': '메시지',
    'form.message_placeholder': '질문이나 의견을 자유롭게 적어 주세요...',
    'form.contact_method': '선호하는 연락 방법',
    'form.method.email': '이메일',
    'form.method.phone': '전화',
    'form.method.either': '모두 가능',
    'form.submit': '문의 제출',
    'form.sending': '전송 중...',

    'success.title': '문의해 주셔서 감사합니다!',
    'success.message1_prefix': '문의가 정상적으로 접수되었으며, ',
    'success.message1_strong': '24시간 이내',
    'success.message1_suffix': '에 답변드리겠습니다.',
    'success.message2': '확인 메일이 다음 주소로 발송되었습니다:',
    'success.close': '닫기',

    'footer.admissions': '입학 안내',
    'footer.apply': '지원하기',
    'footer.requirements': '입학 요건',
    'footer.tuition': '학비 및 재정 지원',
    'footer.about': 'BDS 소개',
    'footer.calendar': '학사 일정',
    'footer.philosophy': '교육 철학',
    'footer.campus_life': '캠퍼스 생활',
    'footer.contact': '문의하기',
    'footer.location': '대한민국 충주',
    'footer.social': '소셜 미디어',
    'footer.copyright': 'Copyright © 2020-2026 BDS (Beyond Dream Scholars). All rights reserved.',

    'header.notice': 'BDS 학사 일정 및 주요 일정',

    'lang.label': '언어',
    'lang.en': 'English',
    'lang.ko': '한국어',
    'lang.ja': '日本語',
    'lang.de': 'Deutsch',

    'calendar.back': '홈으로',
    'calendar.page_title': '2025-2026 학사 일정',
    'calendar.page_subtitle': '학사일정 | BDS Global Leadership Academy',
    'calendar.highlights': '주요 일정',
    'calendar.fall_strong': '가을 학기:',
    'calendar.fall_text': ' 2025년 9월 - 2025년 12월',
    'calendar.winter_strong': '겨울 방학:',
    'calendar.winter_text': ' 2025년 12월 - 2026년 1월',
    'calendar.spring_strong': '봄 학기:',
    'calendar.spring_text': ' 2026년 2월 - 2026년 6월',
    'calendar.summer_strong': '여름 프로그램:',
    'calendar.summer_text': ' 2026년 7월 - 2026년 8월',
    'calendar.events_strong': '특별 행사:',
    'calendar.events_text': ' 모의고사, APAP, 윈터 콘서트, 이스터 에그 헌트 외',
    'calendar.intl_strong': '국제 프로그램:',
    'calendar.intl_text': ' BDS 독일, 서머 세션, SAT/TOEFL 집중반',

    // Ongdalsam campus page
    'ongdalsam.nav_label': '우리 캠퍼스',
    'ongdalsam.card_eyebrow': '우리 캠퍼스',
    'ongdalsam.card_title': '산 속의 캠퍼스',
    'ongdalsam.card_lead': '해발 800m, 깊은 숲에 자리한 BDS의 캠퍼스. 아이가 매일 머물며 배우고 성장하는 바로 그 곳입니다.',
    'ongdalsam.card_cta': '캠퍼스 둘러보기',
    'ongdalsam.hero.eyebrow': '우리 캠퍼스 · 옹달샘',
    'ongdalsam.hero.title': '아이가 살고, 배우고, 자라는 곳',
    'ongdalsam.hero.lead': '해발 800m, 깊은 숲 속에 자리한 BDS 캠퍼스는 학생들이 잠시 머무는 리트릿이 아니라 매일의 일상을 보내는 공간입니다. 배움과 성찰, 건강한 성장을 위해 정성껏 설계된 조용하고 안전한 터전입니다.',
    'ongdalsam.intro.eyebrow': '산 속의 캠퍼스',
    'ongdalsam.intro.title': '23년의 정성으로 다듬어 온 곳',
    'ongdalsam.intro.lead': '2003년에 처음 세워진 비전에서 시작된 캠퍼스입니다 — 젊은 정신이 쉬고, 집중하고, 더 멀리 나아갈 수 있는 배움의 집. 오늘날 BDS의 일상적 환경이 된 이 곳은 숲의 공기와 산의 고요, 그리고 진짜 성장이 가능하도록 지켜내는 리듬을 지닙니다.',
    'ongdalsam.intro.stat1_num': '800 m',
    'ongdalsam.intro.stat1_label': '해발 고도 — 맑은 산 공기, 서늘한 여름, 그리고 조용한 주변 환경',
    'ongdalsam.intro.stat2_num': '23년',
    'ongdalsam.intro.stat2_label': '배움과 내면 성장의 집으로 다듬기 위한 23년간의 지속적인 노력',
    'ongdalsam.intro.stat3_num': '사계절',
    'ongdalsam.intro.stat3_label': '모든 계절에 운영되는 프로그램 — 계절마다 고유한 배움과 생활의 방식이 있습니다',
    'ongdalsam.pillars.eyebrow': '일상을 이루는 네 가지 기둥',
    'ongdalsam.pillars.title': '하루가 만들어지는 방식',
    'ongdalsam.pillars.lead': 'BDS의 학생들은 단지 수업만 듣지 않습니다. 집중된 배움과 꾸준한 성장을 뒷받침하는 네 가지 기둥 위에서 하루를 살아냅니다.',
    'ongdalsam.pillar1.title': '휴식 (Rest)',
    'ongdalsam.pillar1.desc': '하루는 천천히 시작됩니다. 바깥세상의 속도에서 내려와 진짜 집중과 진짜 수면이 가능한 조건을 만듭니다.',
    'ongdalsam.pillar2.title': '움직임 (Movement)',
    'ongdalsam.pillar2.desc': '호흡, 행선(行禪), 무예, 야외 활동으로 이어지는 매일의 몸 수련이 신체의 역량과 정신의 명료함을 함께 지켜줍니다.',
    'ongdalsam.pillar3.title': '명상 (Meditation)',
    'ongdalsam.pillar3.desc': '명상은 가끔의 수업이 아닌 매일의 수행입니다. 학생들은 집중하고, 감정을 알아차리며, 공부의 앞뒤로 고요로 돌아오는 법을 익힙니다.',
    'ongdalsam.pillar4.title': '내면 수행 (Inward Practice)',
    'ongdalsam.pillar4.desc': '독서, 글쓰기, 조용한 성찰, 그리고 진솔한 대화. 대학과 직업, 삶을 위한 필수 역량으로 다룹니다.',
    'ongdalsam.day.eyebrow': '우리 캠퍼스의 하루',
    'ongdalsam.day.title': 'BDS의 하루 리듬',
    'ongdalsam.day.lead': '전형적인 하루는 고요한 시작에서 깊은 학업으로, 다시 성찰로 돌아오는 흐름을 갖습니다. 식사와 움직임, 침묵은 교육의 일부이지 방해가 아닙니다.',
    'ongdalsam.day.t1_label': '아침 명상',
    'ongdalsam.day.t1_desc': '호흡과 자세, 집중으로 시작하는 부드러운 하루 출발.',
    'ongdalsam.day.t2_label': '아침 식사',
    'ongdalsam.day.t2_desc': '신선한 사찰식 유기농 식단을 식당에서 함께 나눕니다.',
    'ongdalsam.day.t3_label': '정규 수업',
    'ongdalsam.day.t3_desc': '영어로 진행되는 소그룹 수업 — 토론, 작문, 과학, 예술.',
    'ongdalsam.day.t4_label': '점심 & 숲 산책',
    'ongdalsam.day.t4_desc': '한낮의 재충전 — 좋은 음식, 맑은 공기, 책에서 떨어진 시간.',
    'ongdalsam.day.t5_label': '선택 과목 & 움직임',
    'ongdalsam.day.t5_desc': '학생이 고른 스포츠, 예술, 무예, 재능 프로그램.',
    'ongdalsam.day.t6_label': '독서와 성찰',
    'ongdalsam.day.t6_desc': '저녁 전, 읽고 쓰고 생각하는 조용한 시간.',
    'ongdalsam.day.t7_label': '저녁 식사',
    'ongdalsam.day.t7_desc': '서두름 없이 함께 나누는 식물 중심의 식사.',
    'ongdalsam.day.t8_label': '저녁 학습 & 마무리 명상',
    'ongdalsam.day.t8_desc': '멘토와 함께하는 집중 학습, 그리고 짧은 명상으로 하루를 닫습니다.',
    'ongdalsam.themes.eyebrow': '7일의 리듬',
    'ongdalsam.themes.title': '요일마다 지니는 주제',
    'ongdalsam.themes.lead': '한 주의 각 요일은 오랜 전통을 지닌 한 글자의 주제를 담습니다. 이 일곱 주제가 어우러져 학업과 움직임, 고요와 공동체 사이를 오가는 주간 리듬을 만듭니다.',
    'ongdalsam.theme1.label': '정 (正)',
    'ongdalsam.theme1.desc': '정직하게 행하기',
    'ongdalsam.theme2.label': '정 (靜)',
    'ongdalsam.theme2.desc': '마음을 가라앉히기',
    'ongdalsam.theme3.label': '동 (動)',
    'ongdalsam.theme3.desc': '건강한 움직임',
    'ongdalsam.theme4.label': '지 (止)',
    'ongdalsam.theme4.desc': '멈추어 알아차리기',
    'ongdalsam.theme5.label': '관 (觀)',
    'ongdalsam.theme5.desc': '또렷이 바라보기',
    'ongdalsam.theme6.label': '화 (和)',
    'ongdalsam.theme6.desc': '함께 어울려 살기',
    'ongdalsam.theme7.label': '청 (淸)',
    'ongdalsam.theme7.desc': '맑고 깨끗한 마음',
    'ongdalsam.facilities.eyebrow': '학생들이 머무는 곳',
    'ongdalsam.facilities.title': '배움을 위해 지어진 공간들',
    'ongdalsam.facilities.lead': '캠퍼스의 모든 공간에는 목적이 있습니다 — 몸을 쉬게 하고, 잘 먹이고, 정신을 모으고, 학생들을 함께 있게 하는 것. 학부모님께 직접 보실 기회를 열어 드립니다.',
    'ongdalsam.facility1.title': '녹온돌집',
    'ongdalsam.facility1.desc': '전통 온돌식 숙소 — 작고 깨끗하며 진짜 쉼을 위해 설계되었습니다. 기숙 담당 교직원의 보살핌 아래 안전하고 평온하게 지냅니다.',
    'ongdalsam.facility2.title': '하늘집',
    'ongdalsam.facility2.desc': '숲을 내다보는 빛이 가득한 열린 생활 공간. 독서, 소담한 대화, 조용한 회복이 이루어지는 곳입니다.',
    'ongdalsam.facility3.title': '식당',
    'ongdalsam.facility3.desc': '사찰식 식사 — 신선하고 제철이며 대부분 식물성입니다. 함께, 서두름 없이 나누는 식사 또한 일상 수행의 일부입니다.',
    'ongdalsam.facility4.title': '명상홀',
    'ongdalsam.facility4.desc': '아침 명상과 저녁 마무리 수행을 위한 조용한 공간. 학생들은 이 곳에서 마음을 가라앉히는 법을 배웁니다.',
    'ongdalsam.facility5.title': '도서관 & 독서실',
    'ongdalsam.facility5.desc': '영어, 한국어를 비롯한 다양한 언어의 장서. 긴 시간 집중할 수 있도록 조용하고 따뜻하게 꾸며졌습니다.',
    'ongdalsam.facility6.title': '숲길 & 야외 공간',
    'ongdalsam.facility6.desc': '산책로와 야외 수련장, 움직임·체육·계절 행사를 위한 열린 땅이 마련되어 있습니다.',
    'ongdalsam.gallery.eyebrow': '이 곳의 풍경',
    'ongdalsam.gallery.title': '캠퍼스 둘러보기',
    'ongdalsam.gallery.lead': 'BDS 학생들이 하루를 보내는 공간의 작은 창. 가족 여러분께서 직접 방문하실 수 있도록 언제든 열려 있습니다.',
    'ongdalsam.parents.eyebrow': '학부모님께',
    'ongdalsam.parents.title': '가족에게 가장 중요한 것들',
    'ongdalsam.parents.lead': '아이를 기숙 캠퍼스에 보내는 것은 의미 있는 결정입니다. 저희가 가장 중요하다고 믿고, 매일 돌보는 것들을 나눕니다.',
    'ongdalsam.parent1.title': '안전과 돌봄',
    'ongdalsam.parent1.desc': '기숙 담당 교직원이 캠퍼스에서 함께 생활합니다. 방은 안전하게 관리되고 건강 상태를 살피며, 아이의 안녕을 가족에게 전합니다.',
    'ongdalsam.parent2.title': '건강한 일상',
    'ongdalsam.parent2.desc': '맑은 산 공기, 사찰식 식사, 충분한 수면, 그리고 학습·움직임·휴식이 균형을 이루는 하루 리듬.',
    'ongdalsam.parent3.title': '집중된 배움',
    'ongdalsam.parent3.desc': '도시의 산만함에서 떨어진 캠퍼스, 소규모 학급, 학생 한 명 한 명의 이름을 아는 멘토들.',
    'ongdalsam.parent4.title': '가족에게 열린 학교',
    'ongdalsam.parent4.desc': '학부모님을 캠퍼스로 모시고, 하루의 일과를 함께 보시고, 교사·기숙 담당자와 직접 이야기 나누실 수 있도록 안내합니다.',
    'ongdalsam.cta.title': '직접 캠퍼스를 보러 오세요',
    'ongdalsam.cta.lead': 'BDS를 가장 잘 이해하시는 방법은 숲에 서 보시고, 식사를 함께 나누시며, 하루가 펼쳐지는 모습을 지켜보시는 것입니다. 가족 여러분을 따뜻하게 초대합니다.',
    'ongdalsam.cta.visit': '방문 예약',
    'ongdalsam.cta.contact': '입학 문의'
  },

  ja: {
    'hero.subtext': '世界中のBDSの学生、教員、職員、卒業生は日々、自らのスキルと知識、エネルギーを公益のために注ぎ、社会に永続的な影響を与えることに取り組んでいます。',

    'cta.title_line1': '目的・卓越性・マインドフルネスで',
    'cta.title_line2': 'グローバルリーダーを育てます',
    'cta.subtitle': 'Beyond Dream Scholarsは、自分自身を超えて夢を描く情熱的な学習者を育み、厳格な学業と毎日の瞑想、人格形成を融合させます。',
    'cta.apply': '今すぐ出願',
    'cta.calendar': '学年暦を見る',
    'cta.visit': '訪問予約',

    'quick_facts.title': '数字で見るBDS',
    'quick_facts.subtitle': '成果と献身で測る教育の卓越性',
    'quick_facts.years.label': '卓越の年数',
    'quick_facts.years.desc': '2020年より',
    'quick_facts.ratio.label': '生徒と教員の比率',
    'quick_facts.ratio.desc': 'すべての生徒に個別の関心を',
    'quick_facts.acceptance.label': '大学進学率',
    'quick_facts.acceptance.desc': '世界で活躍する卒業生たち',
    'quick_facts.countries.label': '参加国数',
    'quick_facts.countries.desc': '真にグローバルなコミュニティ',

    'news.item1.title': '世界水準のインターナショナルスクールBDS',
    'news.item1.desc': 'BDSでは従来の枠を超え、相互につながる世界で卓越と誠実さをもって導く生徒を育てる、世界水準の教育を提供しています。',
    'news.item2.title': 'Beyond Dream, Beyond Border - ドイツ',
    'news.item2.desc': 'BDSドイツ:厳格な学問的卓越とグローバルな機会をつなぎます。生徒たちが境界を越え、夢を現実に変えられるよう力づけます。',
    'news.item3.title': 'オンダルセムでのBDSサマーキャンプ',
    'news.item3.desc': '自然とグローバルビジョンが交わる変化の時間。マインドフルな成長と森の冒険を通じて、生徒が夢の先へ進めるよう導きます。',
    'news.item4.title': 'BDS公式紹介',
    'news.item4.desc': "生徒たちが「夢の先の夢」—個の情熱と世界への貢献が出会う地点—を実現できるよう力づけます。自らの使命を見いだし、それを広げて他者の幸福に資するリーダーを育てます。",

    'philosophy.title': '教育理念とコアバリュー',
    'philosophy.subtitle': 'BDSは学業指導を超え、内面の成長、目的意識、そして世界的責任の涵養に重きを置きます。',
    'philosophy.dream.title': 'Dream Beyond a Dream',
    'philosophy.dream.desc': '生徒が自らの夢を見つけるだけでなく、その夢を他者の幸福と福祉に資するように広げていけるよう導きます。',
    'philosophy.global.title': 'グローバル市民意識',
    'philosophy.global.desc': '意味あるグローバルコミュニケーションの道具としての英語。世界の舞台で活躍できる、説得力と自信を備えたグローバルリーダーを育てます。',
    'philosophy.meditation.title': '瞑想と内面の成長',
    'philosophy.meditation.desc': '毎日の瞑想を通して、生徒は穏やかな自然環境の中で内省し、感情を整え、内なるレジリエンスを育みます。',

    'curriculum.title': 'カリキュラムと学術プログラム',
    'curriculum.subtitle': 'BDSは、国際水準の学力を培うよう体系的に設計されたカリキュラムを運営しています。',
    'curriculum.american.heading': 'アメリカ式カリキュラムと英語イマージョン',
    'curriculum.intl.title': '国際カリキュラム',
    'curriculum.intl.desc': 'アメリカ、イギリス、オーストラリアなどで公認された資格をもつ教員が英語で授業を行います。',
    'curriculum.student.title': '生徒中心の学び',
    'curriculum.student.desc': 'ソクラテス式対話、ディベート、プロジェクト型学習が批判的思考と自主的成長を促します。',
    'curriculum.divisions.title': '学部構成',
    'curriculum.divisions.desc': '初等・中等・高等部に分かれ、国際基準に沿った年齢別カリキュラムを提供します。',
    'curriculum.enrichment.heading': '放課後・発展プログラム',
    'curriculum.talent.title': '才能発見',
    'curriculum.talent.desc': '生徒一人ひとりの固有の才能と強みを探る専用セッションを行います。',
    'curriculum.reading.title': '読書文化',
    'curriculum.reading.desc': '夜の読書プログラムが文学を通して知恵と共感を育みます。',
    'curriculum.nature.title': '自然学習',
    'curriculum.nature.desc': '野外での学びが観察力、マインドフルネス、自然への感受性を高めます。',

    'environment.title': '教育環境と施設',
    'environment.subtitle': 'BDSは自然豊かな地域にあり、学びと心身の健康の双方に最適な環境を提供します。',
    'environment.campus.title': 'キャンパス環境',
    'environment.campus.desc': '最新の教育技術を備えた現代的な教室、実験室、学習スペースを運営しています。',
    'environment.dorm.desc': 'コミュニティと個の成長を育む、安全で快適な寮施設です。',
    'environment.dining.title': 'ダイニングホール',
    'environment.dining.desc': 'お寺式で調理された栄養豊かなオーガニック食事が、健康とマインドフルネスを支えます。',
    'environment.library.title': '図書館と学習資料',
    'environment.library.desc': '深い学びと研究のための広範な蔵書とデジタル資料を揃えています。',
    'environment.wellness.title': 'ウェルネス空間',
    'environment.wellness.desc': '新鮮なオーガニック食事と自然環境が、精神の明晰さと情緒のバランスを高めます。',
    'environment.meditation.title': '瞑想・内省センター',
    'environment.meditation.desc': '毎日の瞑想、集会、静かな内省のための専用空間で、穏やかな自然の中で内なる力、情緒のバランス、マインドフルなリーダーシップを育むよう設計されています。',

    'community.title': 'コミュニティと生徒のウェルビーイング',
    'community.subtitle': 'BDSでは、すべての生徒が個別のケアとサポートを受けます。',
    'community.mentorship.title': '個別メンターシップ',
    'community.mentorship.desc': '8〜12名の少人数クラスで、教員が生徒一人ひとりのニーズと学び方に合わせた指導を行います。',
    'community.respect.title': 'リスペクトの文化',
    'community.respect.desc': '競争よりも誠実さ、共感、協力を大切にする支え合いのコミュニティを育みます。',
    'community.health.title': '包括的ヘルスケア',
    'community.health.desc': '新鮮なオーガニック食事が身体の健康を支え、澄んだ空気と自然が精神の明晰さを高めます。',

    'creativity.title': '創造性と体育',
    'creativity.subtitle': 'BDSは学業の枠を超えて、生徒一人ひとりの可能性を最大限に引き出すことを信条としています。',
    'creativity.artistic.title': '創造的・芸術的表現',
    'creativity.artistic.desc': 'Vlog制作、映像制作、コンテンツ制作、絵画、ブレイクダンス、音楽コンサートなど多彩な芸術活動を支援します。',
    'creativity.sports.title': 'アウトドア・スポーツプログラム',
    'creativity.sports.desc': 'ボート、屋内水泳、乗馬、ゴルフなど、一般の学校では得がたい機会を提供します。',
    'creativity.mentorship.title': '専門家メンターシップ',
    'creativity.mentorship.desc': 'さまざまな分野の専門家(Master Group)が実践的な指導とインスピレーションを提供します。',
    'creativity.events.title': '生徒主導のイベント',
    'creativity.events.desc': '生徒が公演やイベントを自ら企画し導くことで、主体性とリーダーシップを育む意味深い機会を生み出します。',
    'creativity.performance.title': '公演・ステージの機会',
    'creativity.performance.desc': '生徒はコンサート、展示、ショーケース、公演を通じて才能を定期的に披露し、自信、舞台表現力、発信力を養います。',
    'creativity.fitness.title': '体力とウェルネストレーニング',
    'creativity.fitness.desc': '体系的なフィットネス・コンディショニングプログラムが体力、規律、レジリエンスを育み、競技パフォーマンスと生涯のウェルビーイングを支えます。',

    'faq.title': 'よくあるご質問',
    'faq.subtitle': 'BDSの入学、学業、キャンパス生活に関するよくあるご質問にお答えします',
    'faq.q1': 'BDSの入学要件は何ですか?',
    'faq.a1.p1': 'BDSは学業的な潜在力、知的好奇心、そして自己成長への意欲を示す9-12学年の生徒を受け入れています。出願の流れは次のとおりです:',
    'faq.a1.li1': '自己紹介エッセイを含む出願書類',
    'faq.a1.li2': '在籍校の成績証明書',
    'faq.a1.li3': '英語能力試験(海外出願者はTOEFL/IELTS)',
    'faq.a1.li4': '教員推薦状2通',
    'faq.a1.li5': '入学審査委員会との面接',
    'faq.a1.p2': '成績だけでなく、人格、動機、教育理念との調和まで含めて、出願者お一人おひとりを総合的に評価します。',
    'faq.q2': 'BDSの瞑想プログラムのユニークな点は?',
    'faq.a2.p1': 'BDSは毎日の瞑想を正規カリキュラムに組み込んだ、世界でも数少ない学校のひとつです。毎朝20〜30分のガイド瞑想で一日を始め、次のことを目的としています:',
    'faq.a2.li1': '学業のための集中力と精神の明晰さを養う',
    'faq.a2.li2': '情緒的レジリエンスとストレスマネジメント能力を育む',
    'faq.a2.li3': 'マインドフルネスと自己認識を深める',
    'faq.a2.li4': '内なる平穏とバランスある意思決定を培う',
    'faq.a2.p2': '生徒たちは、瞑想が大学出願期のストレス管理、集中力の向上、情緒のバランス維持に役立つと一貫して語っており、これらの力は大学進学後やその先にも受け継がれます。',
    'faq.q3': '「Dream Beyond a Dream」の理念とは?',
    'faq.a3.p1': '「Dream Beyond a Dream」は、生徒が個人的成功の先を見据えるよう促すBDSの中核的教育理念です。自分だけのために夢見るのではなく、次のように問いかけることを勧めています:',
    'faq.a3.li1': '「私の夢はどのように他者の役に立てるだろうか?」',
    'faq.a3.li2': '「コミュニティと世界にどのような良い影響を与えられるか?」',
    'faq.a3.li3': '「自分の才能を世界的な課題の解決にどう生かせるか?」',
    'faq.a3.p2': 'この理念はカリキュラムから社会貢献プロジェクトまであらゆる領域を貫き、学業的に優れているだけでなく、社会的責任を担うグローバル市民としての卒業生を育みます。',
    'faq.q4': 'BDSはどのようにトップ大学への進学を準備しますか?',
    'faq.a4.p1': 'BDSは総合的な大学準備を通じて、100%の大学進学率を維持しています:',
    'faq.a4.li1_strong': '厳格な学業:',
    'faq.a4.li1_text': ' AP科目、SAT/TOEFL対策、大学レベルのライティング指導',
    'faq.a4.li2_strong': '少人数クラス:',
    'faq.a4.li2_text': ' 生徒と教員の比率8:1による個別指導',
    'faq.a4.li3_strong': '大学カウンセリング:',
    'faq.a4.li3_text': ' 専任カウンセラーが出願書類、エッセイ、面接をサポート',
    'faq.a4.li4_strong': '課外活動:',
    'faq.a4.li4_text': ' リーダーシップの機会、社会奉仕、独自のプログラム',
    'faq.a4.li5_strong': 'グローバルな視野:',
    'faq.a4.li5_text': ' 多国籍の生徒構成が多様なキャンパス環境への適応力を育む',
    'faq.a4.p2': '卒業生はStanford、UC Berkeley、Yale、MITをはじめ、韓国、英国、その他世界の有力大学へ進学しています。',
    'faq.q5': 'BDSのキャンパスライフはどのようなものですか?',
    'faq.a5.p1': 'BDSのキャンパスライフは、厳格な学業と全人的な成長をバランスよく両立します:',
    'faq.a5.li1_strong': '自然環境:',
    'faq.a5.li1_text': ' 忠州の静かな田園地帯に位置し、穏やかな学習環境を提供',
    'faq.a5.li2_strong': '寮コミュニティ:',
    'faq.a5.li2_text': ' 寮生活が自立心と深い友情を育む',
    'faq.a5.li3_strong': '国際的な環境:',
    'faq.a5.li3_text': ' 15カ国以上から集う生徒たちが真にグローバルなコミュニティを形成',
    'faq.a5.li4_strong': '一日の流れ:',
    'faq.a5.li4_text': ' 朝の瞑想、授業、スポーツ・芸術、夜の自習、コミュニティの時間',
    'faq.a5.li5_strong': '健やかな生活:',
    'faq.a5.li5_text': ' お寺式のオーガニック食事、アウトドア活動、ウェルネスプログラム',
    'faq.a5.p2': '生徒たちはBDSを、学業・情緒・精神の面で成長できる支え合う家族のようなコミュニティと語ります。',
    'faq.q6': '学費や奨学金はどうなっていますか?',
    'faq.a6.p1': 'BDSは包括的な学費パッケージと経済的支援を用意しています:',
    'faq.a6.li1_strong': '学費:',
    'faq.a6.li1_text': ' 学業、寮、食事、大部分の活動費を含みます',
    'faq.a6.li2_strong': '成績奨学金:',
    'faq.a6.li2_text': ' 学業または リーダーシップで優秀な生徒に提供',
    'faq.a6.li3_strong': '必要に応じた支援:',
    'faq.a6.li3_text': ' 経済的必要のあるご家庭への支援制度',
    'faq.a6.li4_strong': '納付プラン:',
    'faq.a6.li4_text': ' 柔軟なお支払い方法をご利用いただけます',
    'faq.a6.p2': '優れた教育は誰にでも開かれているべきだと考えています。詳しい学費や経済的支援のご相談はadmin@bds-korea.org、または+82-70-7525-5517までお問い合わせください。',
    'faq.cta_text': 'さらにご質問がありますか?',
    'faq.cta_button': '入学のお問い合わせ',

    'form.title': 'BDS入学事務局へのお問い合わせ',
    'form.subtitle': 'お気軽にご連絡ください',
    'form.fullName': 'お名前',
    'form.fullName_placeholder': 'お名前をご入力ください',
    'form.email': 'メールアドレス',
    'form.email_placeholder': 'your.email@example.com',
    'form.phone': '電話番号',
    'form.phone_placeholder': '+82 10-1234-5678',
    'form.country': '国',
    'form.country_select': '国を選択',
    'form.country.kr': '韓国',
    'form.country.us': 'アメリカ',
    'form.country.cn': '中国',
    'form.country.jp': '日本',
    'form.country.vn': 'ベトナム',
    'form.country.th': 'タイ',
    'form.country.other': 'その他',
    'form.grade': '学年',
    'form.grade_select': '学年を選択',
    'form.grade.9': '9年生 (Freshman)',
    'form.grade.10': '10年生 (Sophomore)',
    'form.grade.11': '11年生 (Junior)',
    'form.grade.12': '12年生 (Senior)',
    'form.grade.other': 'その他 / 該当なし',
    'form.inquiry': 'お問い合わせの種類',
    'form.inquiry_select': 'お問い合わせの種類を選択',
    'form.inquiry.admission': '入学要件',
    'form.inquiry.tour': 'キャンパスツアーの予約',
    'form.inquiry.tuition': '学費・経済支援',
    'form.inquiry.programs': '学術プログラム',
    'form.inquiry.life': 'キャンパスライフ',
    'form.inquiry.other': 'その他のご質問',
    'form.message': 'メッセージ',
    'form.message_placeholder': 'ご質問やご意見をご自由にお書きください...',
    'form.contact_method': 'ご希望の連絡方法',
    'form.method.email': 'メール',
    'form.method.phone': '電話',
    'form.method.either': 'どちらでも',
    'form.submit': '送信',
    'form.sending': '送信中...',

    'success.title': 'お問い合わせありがとうございます!',
    'success.message1_prefix': 'お問い合わせを受け付けました。',
    'success.message1_strong': '24時間以内',
    'success.message1_suffix': 'にご返信いたします。',
    'success.message2': '確認メールを以下のアドレスにお送りしました:',
    'success.close': '閉じる',

    'footer.admissions': '入学案内',
    'footer.apply': '今すぐ出願',
    'footer.requirements': '入学要件',
    'footer.tuition': '学費・経済支援',
    'footer.about': 'BDSについて',
    'footer.calendar': '学年暦',
    'footer.philosophy': '教育理念',
    'footer.campus_life': 'キャンパスライフ',
    'footer.contact': 'お問い合わせ',
    'footer.location': '韓国 忠州',
    'footer.social': 'ソーシャルメディア',
    'footer.copyright': 'Copyright © 2020-2026 BDS (Beyond Dream Scholars). All rights reserved.',

    'header.notice': 'BDS学年暦とハイライト',

    'lang.label': '言語',
    'lang.en': 'English',
    'lang.ko': '한국어',
    'lang.ja': '日本語',
    'lang.de': 'Deutsch',

    'calendar.back': 'ホームへ戻る',
    'calendar.page_title': '2025-2026 学年暦',
    'calendar.page_subtitle': '学年暦 | BDS Global Leadership Academy',
    'calendar.highlights': '主な予定',
    'calendar.fall_strong': '秋学期:',
    'calendar.fall_text': ' 2025年9月 - 2025年12月',
    'calendar.winter_strong': '冬休み:',
    'calendar.winter_text': ' 2025年12月 - 2026年1月',
    'calendar.spring_strong': '春学期:',
    'calendar.spring_text': ' 2026年2月 - 2026年6月',
    'calendar.summer_strong': '夏期プログラム:',
    'calendar.summer_text': ' 2026年7月 - 2026年8月',
    'calendar.events_strong': '特別行事:',
    'calendar.events_text': ' 模擬試験、APAP、ウインターコンサート、イースターエッグハント ほか',
    'calendar.intl_strong': '国際プログラム:',
    'calendar.intl_text': ' BDSドイツ、サマーセッション、SAT/TOEFL集中コース',

    // Ongdalsam campus page
    'ongdalsam.nav_label': '私たちのキャンパス',
    'ongdalsam.card_eyebrow': '私たちのキャンパス',
    'ongdalsam.card_title': '山のキャンパス',
    'ongdalsam.card_lead': '海抜800m、深い森の中に広がるBDSのキャンパス。お子さまが日々を過ごし、学び、成長する場所をご覧ください。',
    'ongdalsam.card_cta': 'キャンパスを見る',
    'ongdalsam.hero.eyebrow': '私たちのキャンパス · オンダルセム',
    'ongdalsam.hero.title': 'お子さまが暮らし、学び、育つ場所',
    'ongdalsam.hero.lead': '海抜800m、深い山間の森に広がる私たちのキャンパスは、生徒たちが一時的に訪れるリトリートではなく、毎日を過ごす場です。学びと省察、健やかな成長のために心を込めて整えた、静かで安全な拠点です。',
    'ongdalsam.intro.eyebrow': '山の中のキャンパス',
    'ongdalsam.intro.title': '23年の意志によって育てられた場所',
    'ongdalsam.intro.lead': '2003年に初めて掲げられたビジョンから生まれたキャンパスです — 若い心が休み、集中し、より遠くへ向かえる学びの家を築くという構想です。かつての夢は今やBDSの日常の環境となり、森の空気、山の静けさ、そして本当の成長を守り育てるリズムを備えています。',
    'ongdalsam.intro.stat1_num': '800 m',
    'ongdalsam.intro.stat1_label': '海抜 — 澄んだ山の空気、涼しい夏、静かな環境',
    'ongdalsam.intro.stat2_num': '23年',
    'ongdalsam.intro.stat2_label': '学びと内面の成長の家として整えるための、絶えざる歩み',
    'ongdalsam.intro.stat3_num': '四季',
    'ongdalsam.intro.stat3_label': 'すべての季節に運営されるプログラム — 季節ごとに独自の学びと暮らしがあります',
    'ongdalsam.pillars.eyebrow': '日々を支える四つの柱',
    'ongdalsam.pillars.title': '一日の組み立て方',
    'ongdalsam.pillars.lead': 'BDSの生徒は授業に参加するだけではありません。集中した学びと着実な成長を支える四つの柱の上に、一日を生きています。',
    'ongdalsam.pillar1.title': '休息 (Rest)',
    'ongdalsam.pillar1.desc': '一日は穏やかに始まります。外の世界の速度から降り立ち、本当の集中と本当の眠りが可能になる条件をつくります。',
    'ongdalsam.pillar2.title': '動 (Movement)',
    'ongdalsam.pillar2.desc': '呼吸、歩く瞑想、武道、野外での活動といった日々の身体修練が、体の能力と心の明晰さを同時に守ります。',
    'ongdalsam.pillar3.title': '瞑想 (Meditation)',
    'ongdalsam.pillar3.desc': '瞑想は時折の授業ではなく、毎日の実践です。生徒は集中することを学び、感情に気づき、学びの前後で静けさに戻る方法を身につけます。',
    'ongdalsam.pillar4.title': '内なる修練 (Inward Practice)',
    'ongdalsam.pillar4.desc': '読書、書くこと、静かな省察、そして誠実な対話。大学、仕事、人生に必要な力として大切にします。',
    'ongdalsam.day.eyebrow': 'キャンパスの一日',
    'ongdalsam.day.title': 'BDSの一日のリズム',
    'ongdalsam.day.lead': '典型的な一日は、静かな始まりから深い学業へ、そして再び省察へと巡ります。食事、動き、沈黙は教育の一部であり、妨げではありません。',
    'ongdalsam.day.t1_label': '朝の瞑想',
    'ongdalsam.day.t1_desc': '呼吸、姿勢、集中で始める穏やかな一日のスタート。',
    'ongdalsam.day.t2_label': '朝食',
    'ongdalsam.day.t2_desc': '新鮮な寺院式のオーガニック食事を食堂でともに味わいます。',
    'ongdalsam.day.t3_label': '正規の授業',
    'ongdalsam.day.t3_desc': '英語による少人数授業 — ディスカッション、ライティング、サイエンス、アート。',
    'ongdalsam.day.t4_label': '昼食と森の散歩',
    'ongdalsam.day.t4_desc': '昼のリセット — 良い食事、澄んだ空気、本から離れる時間。',
    'ongdalsam.day.t5_label': '選択科目と身体活動',
    'ongdalsam.day.t5_desc': '生徒が選ぶスポーツ、アート、武道、才能プログラム。',
    'ongdalsam.day.t6_label': '読書と省察',
    'ongdalsam.day.t6_desc': '夕方の前に、読み、書き、考える静かな時間。',
    'ongdalsam.day.t7_label': '夕食',
    'ongdalsam.day.t7_desc': '急がず、植物中心でともに分かち合う食事。',
    'ongdalsam.day.t8_label': '夜の学習と締めの瞑想',
    'ongdalsam.day.t8_desc': 'メンターと行う集中学習の後、短い瞑想で一日を閉じます。',
    'ongdalsam.themes.eyebrow': '七日のリズム',
    'ongdalsam.themes.title': '曜日ごとのテーマ',
    'ongdalsam.themes.lead': '一週間の各曜日は、長い伝統を持つ一文字の主題を帯びます。これら七つの主題が合わさり、学業と動き、静けさと共同体のあいだを行き来する週のリズムを形作ります。',
    'ongdalsam.theme1.label': '正',
    'ongdalsam.theme1.desc': '正直に行う',
    'ongdalsam.theme2.label': '靜',
    'ongdalsam.theme2.desc': '心を落ち着ける',
    'ongdalsam.theme3.label': '動',
    'ongdalsam.theme3.desc': '健やかな動き',
    'ongdalsam.theme4.label': '止',
    'ongdalsam.theme4.desc': '止まって気づく',
    'ongdalsam.theme5.label': '觀',
    'ongdalsam.theme5.desc': 'はっきり見る',
    'ongdalsam.theme6.label': '和',
    'ongdalsam.theme6.desc': 'ともに和らぐ',
    'ongdalsam.theme7.label': '淸',
    'ongdalsam.theme7.desc': '澄んだ清らかな心',
    'ongdalsam.facilities.eyebrow': '生徒が暮らす場所',
    'ongdalsam.facilities.title': '学びのためにつくられた空間',
    'ongdalsam.facilities.lead': 'キャンパスのすべての空間には目的があります — 体を休ませ、しっかり養い、心を集め、生徒たちをつなぐこと。ご家族は直接いらしてご覧いただけます。',
    'ongdalsam.facility1.title': '緑オンドル棟',
    'ongdalsam.facility1.desc': '伝統的なオンドル式の居室 — 小さく、清潔で、本当の休息のために整えられています。住み込みスタッフの見守りのもと、穏やかで安全に過ごせます。',
    'ongdalsam.facility2.title': '白い空の家',
    'ongdalsam.facility2.desc': '森を見晴らす、光あふれる開かれた居室。読書、静かな会話、回復のひとときが日々行われます。',
    'ongdalsam.facility3.title': '食堂',
    'ongdalsam.facility3.desc': '寺院式の食事 — 新鮮で季節に即し、ほとんどが植物性です。急がず、ともに分かち合う食事もまた日々の実践の一部です。',
    'ongdalsam.facility4.title': '瞑想ホール',
    'ongdalsam.facility4.desc': '朝の瞑想、夜の締めの修行のための静かなホール。生徒はここで心を落ち着ける意味を学びます。',
    'ongdalsam.facility5.title': '図書館と読書室',
    'ongdalsam.facility5.desc': '英語、韓国語をはじめ多様な言語の蔵書。静かで暖かく、長い時間の読書と研究に向いた空間です。',
    'ongdalsam.facility6.title': '森の小径と屋外空間',
    'ongdalsam.facility6.desc': '散策路、野外の修練場、動き・スポーツ・季節の行事のための開かれた土地があります。',
    'ongdalsam.gallery.eyebrow': 'この場所',
    'ongdalsam.gallery.title': 'キャンパスの眺め',
    'ongdalsam.gallery.lead': 'BDSの生徒たちが一日を過ごす場所の小さな窓です。ご家族にはいつでもお越しいただけます。',
    'ongdalsam.parents.eyebrow': '保護者の皆さまへ',
    'ongdalsam.parents.title': 'ご家族にとって最も大切なこと',
    'ongdalsam.parents.lead': 'お子さまを寄宿のキャンパスへ送り出すことは大きな意思決定です。私たちが最も大切だと信じ、毎日取り組んでいることをお伝えします。',
    'ongdalsam.parent1.title': '安全とケア',
    'ongdalsam.parent1.desc': '住み込みのスタッフがキャンパスに在住します。居室は見守られ、健康状態は見守り、ご家族にはお子さまの様子を共有します。',
    'ongdalsam.parent2.title': '健やかな日常',
    'ongdalsam.parent2.desc': '澄んだ山の空気、寺院式の食事、十分な睡眠、学び・動き・休息が均衡する一日のリズム。',
    'ongdalsam.parent3.title': '集中した学び',
    'ongdalsam.parent3.desc': '都市の喧騒から離れたキャンパス、少人数クラス、生徒一人ひとりの名前を知るメンターたち。',
    'ongdalsam.parent4.title': 'ご家族に開かれた学校',
    'ongdalsam.parent4.desc': '保護者の皆さまをキャンパスへお招きし、一日の流れをご一緒にご覧いただき、教員・住み込みスタッフと直接お話しいただけます。',
    'ongdalsam.cta.title': '直接キャンパスをご覧に',
    'ongdalsam.cta.lead': 'BDSを最もよくご理解いただく方法は、森に立ち、食事をともにし、一日が広がる様子を見届けることです。ご家族を心よりお迎えします。',
    'ongdalsam.cta.visit': '訪問予約',
    'ongdalsam.cta.contact': '入学のお問い合わせ'
  },

  de: {
    'hero.subtext': 'Tag für Tag setzen BDS-Schülerinnen und -Schüler, Lehrkräfte, Mitarbeitende und Ehemalige weltweit ihre Fähigkeiten, ihr Wissen und ihre Energie für das Gemeinwohl ein und hinterlassen nachhaltige Spuren in der Gesellschaft.',

    'cta.title_line1': 'Globale Führungspersönlichkeiten bilden –',
    'cta.title_line2': 'mit Sinn, Exzellenz und Achtsamkeit',
    'cta.subtitle': 'Beyond Dream Scholars fördert leidenschaftliche Lernende, die über sich hinaus träumen, und verbindet anspruchsvolle Akademik mit täglicher Meditation und Persönlichkeitsbildung.',
    'cta.apply': 'Jetzt bewerben',
    'cta.calendar': 'Akademischen Kalender ansehen',
    'cta.visit': 'Besuch vereinbaren',

    'quick_facts.title': 'BDS in Zahlen',
    'quick_facts.subtitle': 'Bildungsqualität, messbar an Ergebnissen und Engagement',
    'quick_facts.years.label': 'Jahre der Exzellenz',
    'quick_facts.years.desc': 'Seit 2020',
    'quick_facts.ratio.label': 'Betreuungsverhältnis',
    'quick_facts.ratio.desc': 'Individuelle Aufmerksamkeit für jede Schülerin und jeden Schüler',
    'quick_facts.acceptance.label': 'Universitätszulassung',
    'quick_facts.acceptance.desc': 'Unsere Absolventen sind weltweit erfolgreich',
    'quick_facts.countries.label': 'Vertretene Länder',
    'quick_facts.countries.desc': 'Eine wahrhaft globale Gemeinschaft',

    'news.item1.title': 'BDS – eine internationale Schule auf Weltniveau',
    'news.item1.desc': 'An der BDS überwinden wir traditionelle Grenzen und bieten eine Bildung auf Weltniveau, die Schülerinnen und Schüler darauf vorbereitet, in einer vernetzten Welt mit Exzellenz und Integrität Verantwortung zu übernehmen.',
    'news.item2.title': 'Beyond Dream, Beyond Border – Deutschland',
    'news.item2.desc': 'BDS Deutschland: Die Brücke zwischen hoher akademischer Exzellenz und globalen Chancen. Wir befähigen unsere Schülerinnen und Schüler, Grenzen zu überwinden und Träume Wirklichkeit werden zu lassen.',
    'news.item3.title': 'BDS-Sommercamp in Ongdalsam',
    'news.item3.desc': 'Ein verwandelndes Retreat, bei dem Natur auf globale Vision trifft. Durch achtsames Wachstum und Walderlebnisse gehen die Lernenden über ihre Träume hinaus.',
    'news.item4.title': 'Offizielle BDS-Vorstellung',
    'news.item4.desc': "Wir ermutigen die Schülerinnen und Schüler, „Dreams Beyond Dreams“ zu verwirklichen — wo persönliche Leidenschaft auf globalen Beitrag trifft. Wir bilden Persönlichkeiten, die ihre Bestimmung finden und sie für das Glück anderer einsetzen.",

    'philosophy.title': 'Bildungsphilosophie und Grundwerte',
    'philosophy.subtitle': 'BDS geht über den klassischen Unterricht hinaus. Wir fördern inneres Wachstum, Sinn und globale Verantwortung.',
    'philosophy.dream.title': 'Dream Beyond a Dream',
    'philosophy.dream.desc': 'Wir begleiten unsere Schülerinnen und Schüler dabei, ihre Träume nicht nur zu entdecken, sondern sie so weiterzudenken, dass sie zum Glück und Wohlergehen anderer beitragen.',
    'philosophy.global.title': 'Globale Bürgerschaft',
    'philosophy.global.desc': 'Englisch als Werkzeug für bedeutungsvolle internationale Kommunikation. Wir bilden überzeugende und selbstbewusste globale Führungspersönlichkeiten aus, die auf der Weltbühne bestehen.',
    'philosophy.meditation.title': 'Meditation und innere Entwicklung',
    'philosophy.meditation.desc': 'Durch tägliche Meditation lernen unsere Schülerinnen und Schüler, zu reflektieren, Emotionen zu regulieren und ihre innere Widerstandskraft in einer ruhigen Naturumgebung zu stärken.',

    'curriculum.title': 'Lehrplan und akademische Programme',
    'curriculum.subtitle': 'BDS führt einen strukturierten Lehrplan, der darauf ausgelegt ist, akademische Kompetenz auf internationalem Niveau aufzubauen.',
    'curriculum.american.heading': 'Curriculum nach US-Modell und Englisch-Immersion',
    'curriculum.intl.title': 'Internationales Curriculum',
    'curriculum.intl.desc': 'Unterricht auf Englisch durch qualifizierte Lehrkräfte, die in den USA, Großbritannien, Australien und weiteren Ländern anerkannt sind.',
    'curriculum.student.title': 'Schülerzentriertes Lernen',
    'curriculum.student.desc': 'Sokratische Methode, Debatten und projektorientiertes Lernen fördern kritisches Denken und eigenverantwortliches Wachstum.',
    'curriculum.divisions.title': 'Schulstufen',
    'curriculum.divisions.desc': 'Grund-, Mittel- und Oberstufe bieten altersgerechte Lehrpläne, die sich an internationalen Standards orientieren.',
    'curriculum.enrichment.heading': 'Nachmittags- und Förderprogramme',
    'curriculum.talent.title': 'Talentförderung',
    'curriculum.talent.desc': 'Eigene Einheiten, um die individuellen Talente und Stärken jeder Schülerin und jedes Schülers zu entdecken.',
    'curriculum.reading.title': 'Lesekultur',
    'curriculum.reading.desc': 'Abendliche Leseprogramme fördern Weisheit und Empathie durch Literatur.',
    'curriculum.nature.title': 'Lernen in der Natur',
    'curriculum.nature.desc': 'Lernerfahrungen im Freien schärfen Beobachtungsgabe, Achtsamkeit und die Wertschätzung der Natur.',

    'environment.title': 'Lernumgebung und Einrichtungen',
    'environment.subtitle': 'BDS liegt in einer naturnahen Umgebung und bietet ideale Bedingungen für Lernen und Wohlbefinden gleichermaßen.',
    'environment.campus.title': 'Campus-Umgebung',
    'environment.campus.desc': 'Moderne Klassenräume, Labore und Lernbereiche, ausgestattet mit neuester Bildungstechnologie.',
    'environment.dorm.desc': 'Sichere und komfortable Wohnräume, die Gemeinschaft und persönliches Wachstum fördern.',
    'environment.dining.title': 'Speisesaal',
    'environment.dining.desc': 'Nahrhafte, biologische Mahlzeiten, zubereitet in einem Speisesaal im Tempelstil, der Gesundheit und Achtsamkeit unterstützt.',
    'environment.library.title': 'Bibliothek und Ressourcen',
    'environment.library.desc': 'Umfangreiche Sammlung an Büchern und digitalen Ressourcen für vertieftes Lernen und Forschung.',
    'environment.wellness.title': 'Wellness-Bereiche',
    'environment.wellness.desc': 'Frische biologische Mahlzeiten und eine natürliche Umgebung fördern geistige Klarheit und emotionale Balance.',
    'environment.meditation.title': 'Meditations- und Reflexionszentrum',
    'environment.meditation.desc': 'Eigene Räume für tägliche Meditation, Versammlungen und stille Reflexion, gestaltet, um innere Stärke, emotionale Balance und achtsame Führung in einer ruhigen Naturumgebung zu fördern.',

    'community.title': 'Gemeinschaft und Wohlbefinden der Lernenden',
    'community.subtitle': 'An der BDS erhält jede Schülerin und jeder Schüler individuelle Zuwendung und Unterstützung.',
    'community.mentorship.title': 'Individuelles Mentoring',
    'community.mentorship.desc': 'Kleine Klassen (8–12 Schülerinnen und Schüler) ermöglichen es den Lehrkräften, den Unterricht auf die jeweiligen Bedürfnisse und Lernstile abzustimmen.',
    'community.respect.title': 'Kultur des Respekts',
    'community.respect.desc': 'Wir fördern eine unterstützende Gemeinschaft, in der Ehrlichkeit, Empathie und Kooperation über Konkurrenz gestellt werden.',
    'community.health.title': 'Ganzheitliche Gesundheit',
    'community.health.desc': 'Frische biologische Mahlzeiten unterstützen die körperliche Gesundheit. Saubere Luft und natürliche Umgebung stärken die geistige Klarheit.',

    'creativity.title': 'Kreativität und Sport',
    'creativity.subtitle': 'BDS ist überzeugt, dass sich das Potenzial jeder Schülerin und jedes Schülers über das Akademische hinaus entfalten lässt.',
    'creativity.artistic.title': 'Kreativer und künstlerischer Ausdruck',
    'creativity.artistic.desc': 'Unterstützung für V-Log-Produktion, Filmemachen, Content Creation, Malerei, Breakdance, Musikkonzerte und weitere künstlerische Aktivitäten.',
    'creativity.sports.title': 'Outdoor- und Sportprogramme',
    'creativity.sports.desc': 'Möglichkeiten, die an typischen Schulen selten sind – darunter Rudern, Hallenschwimmen, Reiten und Golf.',
    'creativity.mentorship.title': 'Mentoring durch Fachleute',
    'creativity.mentorship.desc': 'Expertinnen und Experten aus verschiedenen Bereichen (Master Group) bieten praxisnahe Begleitung und Inspiration.',
    'creativity.events.title': 'Von Schülerinnen und Schülern geleitete Veranstaltungen',
    'creativity.events.desc': 'Die Lernenden planen und leiten Aufführungen und Veranstaltungen und schaffen so wertvolle Gelegenheiten für Eigenverantwortung und Führungswachstum.',
    'creativity.performance.title': 'Auftritts- und Bühnenmöglichkeiten',
    'creativity.performance.desc': 'Regelmäßig präsentieren Schülerinnen und Schüler ihre Talente in Konzerten, Ausstellungen, Showcases und öffentlichen Aufführungen und bauen so Selbstvertrauen, Bühnenpräsenz und Ausdruckskraft auf.',
    'creativity.fitness.title': 'Kraft- und Wellness-Training',
    'creativity.fitness.desc': 'Strukturierte Fitness- und Konditionsprogramme fördern Ausdauer, Disziplin und Resilienz und unterstützen sowohl sportliche Leistung als auch lebenslanges Wohlbefinden.',

    'faq.title': 'Häufig gestellte Fragen',
    'faq.subtitle': 'Antworten auf häufige Fragen zu Zulassung, Akademik und Campusleben an der BDS',
    'faq.q1': 'Wie sind die Zulassungsvoraussetzungen an der BDS?',
    'faq.a1.p1': 'Die BDS nimmt Schülerinnen und Schüler der Klassen 9–12 auf, die akademisches Potenzial, Neugier und den Willen zu persönlichem Wachstum zeigen. Das Bewerbungsverfahren umfasst:',
    'faq.a1.li1': 'Vollständig ausgefülltes Bewerbungsformular mit persönlichem Essay',
    'faq.a1.li2': 'Zeugnisse der bisherigen Schulen',
    'faq.a1.li3': 'Englischsprachtest (TOEFL/IELTS für internationale Bewerberinnen und Bewerber)',
    'faq.a1.li4': 'Zwei Lehrerempfehlungen',
    'faq.a1.li5': 'Interview mit dem Zulassungsausschuss',
    'faq.a1.p2': 'Wir bewerten jede Bewerbung ganzheitlich und berücksichtigen nicht nur Noten, sondern auch Charakter, Motivation und die Übereinstimmung mit unserer Bildungsphilosophie.',
    'faq.q2': 'Was macht das Meditationsprogramm der BDS besonders?',
    'faq.a2.p1': 'Die BDS ist eine der wenigen Schulen weltweit, die tägliche Meditation in den Lehrplan integriert. Jeder Morgen beginnt mit einer 20- bis 30-minütigen geführten Meditation, die Folgendes zum Ziel hat:',
    'faq.a2.li1': 'Fokus und geistige Klarheit für das akademische Arbeiten zu entwickeln',
    'faq.a2.li2': 'Emotionale Resilienz und Stresskompetenz aufzubauen',
    'faq.a2.li3': 'Achtsamkeit und Selbstwahrnehmung zu vertiefen',
    'faq.a2.li4': 'Inneren Frieden und ausgewogene Entscheidungsfindung zu fördern',
    'faq.a2.p2': 'Schülerinnen und Schüler berichten immer wieder, dass die Meditation ihnen hilft, den Stress bei Hochschulbewerbungen zu bewältigen, die Konzentration zu stärken und die emotionale Balance zu halten – Fähigkeiten, die ihnen an der Universität und darüber hinaus erhalten bleiben.',
    'faq.q3': 'Was bedeutet die Philosophie „Dream Beyond a Dream“?',
    'faq.a3.p1': '„Dream Beyond a Dream“ ist die zentrale Bildungsphilosophie der BDS, die Schülerinnen und Schüler herausfordert, über den persönlichen Erfolg hinauszudenken. Statt nur für sich selbst zu träumen, ermutigen wir sie zu fragen:',
    'faq.a3.li1': '„Wie können meine Träume anderen zugutekommen?"',
    'faq.a3.li2': '„Welchen positiven Einfluss kann ich auf meine Gemeinschaft und die Welt haben?"',
    'faq.a3.li3': '„Wie kann ich meine Talente einsetzen, um globale Herausforderungen anzugehen?"',
    'faq.a3.p2': 'Diese Philosophie prägt alles – vom Lehrplan bis zu unseren Sozialprojekten – und bringt Absolventinnen und Absolventen hervor, die nicht nur akademisch erfolgreich, sondern auch sozial verantwortungsvolle Weltbürgerinnen und Weltbürger sind.',
    'faq.q4': 'Wie bereitet die BDS auf Spitzenuniversitäten vor?',
    'faq.a4.p1': 'Die BDS hält eine Universitätszulassungsquote von 100 % durch eine umfassende Studienvorbereitung aufrecht:',
    'faq.a4.li1_strong': 'Anspruchsvolle Akademik:',
    'faq.a4.li1_text': ' AP-Kurse, SAT/TOEFL-Vorbereitung und wissenschaftliches Schreiben auf Universitätsniveau',
    'faq.a4.li2_strong': 'Kleine Klassen:',
    'faq.a4.li2_text': ' Betreuungsverhältnis 8:1 sichert individuelle Begleitung',
    'faq.a4.li3_strong': 'Studienberatung:',
    'faq.a4.li3_text': ' Dedizierte Beraterinnen und Berater unterstützen bei Bewerbungen, Essays und Interviews',
    'faq.a4.li4_strong': 'Extracurriculare Aktivitäten:',
    'faq.a4.li4_text': ' Führungschancen, soziales Engagement und besondere Programme',
    'faq.a4.li5_strong': 'Globale Perspektive:',
    'faq.a4.li5_text': ' Eine internationale Schülerschaft bereitet auf vielfältige Campusumgebungen vor',
    'faq.a4.p2': 'Unsere Absolventinnen und Absolventen wurden an Stanford, UC Berkeley, Yale, MIT sowie an führenden Universitäten in Korea, Großbritannien und darüber hinaus aufgenommen.',
    'faq.q5': 'Wie sieht das Campusleben an der BDS aus?',
    'faq.a5.p1': 'Das Campusleben an der BDS verbindet anspruchsvolle Akademik mit ganzheitlicher Persönlichkeitsentwicklung:',
    'faq.a5.li1_strong': 'Naturnahe Lage:',
    'faq.a5.li1_text': ' In der ruhigen Umgebung von Chungju gelegen, bietet sie ein friedliches Lernumfeld',
    'faq.a5.li2_strong': 'Wohngemeinschaft:',
    'faq.a5.li2_text': ' Das Internatsleben fördert Eigenständigkeit und enge Freundschaften',
    'faq.a5.li3_strong': 'Internationales Umfeld:',
    'faq.a5.li3_text': ' Schülerinnen und Schüler aus mehr als 15 Ländern bilden eine wahrhaft globale Gemeinschaft',
    'faq.a5.li4_strong': 'Tagesablauf:',
    'faq.a5.li4_text': ' Morgenmeditation, Unterricht, Sport und Kunst, abendliches Selbststudium und Gemeinschaftszeit',
    'faq.a5.li5_strong': 'Gesunde Lebensweise:',
    'faq.a5.li5_text': ' Biologische Mahlzeiten im Tempelstil, Outdoor-Aktivitäten und Wellness-Programme',
    'faq.a5.p2': 'Die Lernenden beschreiben die BDS als eine unterstützende Familie, in der sie akademisch, emotional und spirituell wachsen.',
    'faq.q6': 'Wie sehen Schulgeld und finanzielle Unterstützung aus?',
    'faq.a6.p1': 'Die BDS bietet umfassende Gebührenmodelle und finanzielle Unterstützung:',
    'faq.a6.li1_strong': 'Schulgeld:',
    'faq.a6.li1_text': ' Umfasst Unterricht, Unterkunft, Verpflegung und die meisten Aktivitäten',
    'faq.a6.li2_strong': 'Leistungsstipendien:',
    'faq.a6.li2_text': ' Verfügbar für Schülerinnen und Schüler mit herausragenden akademischen oder Führungsleistungen',
    'faq.a6.li3_strong': 'Bedarfsorientierte Unterstützung:',
    'faq.a6.li3_text': ' Finanzielle Hilfe für Familien mit nachgewiesenem Bedarf',
    'faq.a6.li4_strong': 'Zahlungspläne:',
    'faq.a6.li4_text': ' Flexible Zahlungsmodalitäten verfügbar',
    'faq.a6.p2': 'Wir sind überzeugt, dass herausragende Bildung zugänglich sein sollte. Bitte kontaktieren Sie unser Zulassungsbüro unter admin@bds-korea.org oder +82-70-7525-5517 für ausführliche Informationen zum Schulgeld und zur finanziellen Unterstützung.',
    'faq.cta_text': 'Haben Sie weitere Fragen?',
    'faq.cta_button': 'Zulassung kontaktieren',

    'form.title': 'Kontakt zum BDS-Zulassungsbüro',
    'form.subtitle': 'Wir freuen uns, von Ihnen zu hören',
    'form.fullName': 'Vollständiger Name',
    'form.fullName_placeholder': 'Ihren vollständigen Namen eingeben',
    'form.email': 'E-Mail-Adresse',
    'form.email_placeholder': 'ihre.email@example.com',
    'form.phone': 'Telefonnummer',
    'form.phone_placeholder': '+82 10-1234-5678',
    'form.country': 'Land',
    'form.country_select': 'Land auswählen',
    'form.country.kr': 'Südkorea',
    'form.country.us': 'Vereinigte Staaten',
    'form.country.cn': 'China',
    'form.country.jp': 'Japan',
    'form.country.vn': 'Vietnam',
    'form.country.th': 'Thailand',
    'form.country.other': 'Sonstiges',
    'form.grade': 'Klassenstufe',
    'form.grade_select': 'Klassenstufe auswählen',
    'form.grade.9': 'Klasse 9 (Freshman)',
    'form.grade.10': 'Klasse 10 (Sophomore)',
    'form.grade.11': 'Klasse 11 (Junior)',
    'form.grade.12': 'Klasse 12 (Senior)',
    'form.grade.other': 'Sonstiges / nicht zutreffend',
    'form.inquiry': 'Art der Anfrage',
    'form.inquiry_select': 'Art der Anfrage auswählen',
    'form.inquiry.admission': 'Zulassungsvoraussetzungen',
    'form.inquiry.tour': 'Campus-Tour-Anfrage',
    'form.inquiry.tuition': 'Schulgeld und Finanzhilfe',
    'form.inquiry.programs': 'Akademische Programme',
    'form.inquiry.life': 'Campusleben',
    'form.inquiry.other': 'Sonstige Fragen',
    'form.message': 'Nachricht',
    'form.message_placeholder': 'Bitte teilen Sie uns Ihre Fragen oder Anmerkungen mit...',
    'form.contact_method': 'Bevorzugte Kontaktart',
    'form.method.email': 'E-Mail',
    'form.method.phone': 'Telefon',
    'form.method.either': 'Beides möglich',
    'form.submit': 'Anfrage senden',
    'form.sending': 'Wird gesendet...',

    'success.title': 'Vielen Dank für Ihre Kontaktaufnahme!',
    'success.message1_prefix': 'Wir haben Ihre Anfrage erhalten und antworten innerhalb von ',
    'success.message1_strong': '24 Stunden',
    'success.message1_suffix': '.',
    'success.message2': 'Eine Bestätigungs-E-Mail wurde an folgende Adresse gesendet:',
    'success.close': 'Schließen',

    'footer.admissions': 'Zulassung',
    'footer.apply': 'Jetzt bewerben',
    'footer.requirements': 'Zulassungsvoraussetzungen',
    'footer.tuition': 'Schulgeld und Finanzhilfe',
    'footer.about': 'Über BDS',
    'footer.calendar': 'Akademischer Kalender',
    'footer.philosophy': 'Unsere Philosophie',
    'footer.campus_life': 'Campusleben',
    'footer.contact': 'Kontakt',
    'footer.location': 'Chungju, Südkorea',
    'footer.social': 'Folgen Sie uns',
    'footer.copyright': 'Copyright © 2020-2026 BDS (Beyond Dream Scholars). Alle Rechte vorbehalten.',

    'header.notice': 'Akademischer Kalender und Highlights der BDS',

    'lang.label': 'Sprache',
    'lang.en': 'English',
    'lang.ko': '한국어',
    'lang.ja': '日本語',
    'lang.de': 'Deutsch',

    'calendar.back': 'Zurück zur Startseite',
    'calendar.page_title': 'Akademischer Kalender 2025–2026',
    'calendar.page_subtitle': 'Akademischer Kalender | BDS Global Leadership Academy',
    'calendar.highlights': 'Wichtige Termine',
    'calendar.fall_strong': 'Herbstsemester:',
    'calendar.fall_text': ' September 2025 – Dezember 2025',
    'calendar.winter_strong': 'Winterferien:',
    'calendar.winter_text': ' Dezember 2025 – Januar 2026',
    'calendar.spring_strong': 'Frühjahrssemester:',
    'calendar.spring_text': ' Februar 2026 – Juni 2026',
    'calendar.summer_strong': 'Sommerprogramme:',
    'calendar.summer_text': ' Juli 2026 – August 2026',
    'calendar.events_strong': 'Besondere Veranstaltungen:',
    'calendar.events_text': ' Probeklausuren, APAP, Winterkonzert, Ostereiersuche und mehr',
    'calendar.intl_strong': 'Internationale Programme:',
    'calendar.intl_text': ' BDS Deutschland, Sommersessions, Intensivkurse SAT/TOEFL',

    // Ongdalsam campus page
    'ongdalsam.nav_label': 'Unser Campus',
    'ongdalsam.card_eyebrow': 'Unser Campus',
    'ongdalsam.card_title': 'Ein Campus in den Bergen',
    'ongdalsam.card_lead': 'Unser Campus liegt auf 800 Metern Höhe, tief in einem bewaldeten Gebirgszug. Sehen Sie, wo Ihr Kind Tag für Tag lebt, lernt und wächst.',
    'ongdalsam.card_cta': 'Campus entdecken',
    'ongdalsam.hero.eyebrow': 'Unser Campus · Ongdalsam',
    'ongdalsam.hero.title': 'Wo Ihr Kind lebt, lernt und wächst',
    'ongdalsam.hero.lead': 'Auf 800 Metern Höhe, tief in einem bewaldeten Gebirge, ist unser Campus kein Ort, den die Lernenden nur gelegentlich besuchen – hier leben sie jeden Tag. Ein stiller, sicherer und bewusst gestalteter Ort für Lernen, Reflexion und gesundes Wachstum.',
    'ongdalsam.intro.eyebrow': 'Ein Campus in den Bergen',
    'ongdalsam.intro.title': 'Ein Ort, der von 23 Jahren Absicht geformt wurde',
    'ongdalsam.intro.lead': 'Unser Campus ist aus einer Vision von 2003 erwachsen – ein Lernzuhause zu schaffen, in dem junge Menschen zur Ruhe kommen, sich konzentrieren und weiter hinauswachsen können. Was einst ein Traum war, ist heute die alltägliche Umgebung der BDS: Waldluft, Bergstille und ein Rhythmus, der die Bedingungen für echtes Wachstum schützt.',
    'ongdalsam.intro.stat1_num': '800 m',
    'ongdalsam.intro.stat1_label': 'Höhenlage – reine Bergluft, kühlere Sommer und eine ruhige Umgebung',
    'ongdalsam.intro.stat2_num': '23 Jahre',
    'ongdalsam.intro.stat2_label': 'Kontinuierliche Arbeit, um diesen Ort zu einem Zuhause für Lernen und inneres Wachstum zu gestalten',
    'ongdalsam.intro.stat3_num': '4 Jahreszeiten',
    'ongdalsam.intro.stat3_label': 'Aktives Programm – jede Jahreszeit bringt ihre eigene Art zu lernen und zu leben',
    'ongdalsam.pillars.eyebrow': 'Vier Grundpfeiler des Alltags',
    'ongdalsam.pillars.title': 'Wie jeder Tag aufgebaut ist',
    'ongdalsam.pillars.lead': 'Lernende an der BDS besuchen nicht nur den Unterricht – sie leben einen strukturierten Tag, der auf vier Grundpfeilern ruht, die konzentriertes Lernen und stetiges Wachsen tragen.',
    'ongdalsam.pillar1.title': 'Ruhe',
    'ongdalsam.pillar1.desc': 'Der Tag beginnt behutsam. Die Lernenden treten aus dem Tempo der äußeren Welt heraus, damit echte Konzentration und echter Schlaf möglich werden.',
    'ongdalsam.pillar2.title': 'Bewegung',
    'ongdalsam.pillar2.desc': 'Tägliche Körperarbeit – Atem, Gehmeditation, Kampfkunst und Bewegung im Freien – hält den Körper leistungsfähig und den Geist klar.',
    'ongdalsam.pillar3.title': 'Meditation',
    'ongdalsam.pillar3.desc': 'Geführte Meditation ist tägliche Praxis, keine gelegentliche Lektion. Die Lernenden üben Konzentration, nehmen Gefühle wahr und kehren vor und nach dem Lernen in die Stille zurück.',
    'ongdalsam.pillar4.title': 'Innere Praxis',
    'ongdalsam.pillar4.desc': 'Lesen, Schreiben, stille Reflexion und ehrliches Gespräch. Wir behandeln sie als wesentliche Fähigkeiten für Universität, Beruf und Leben – nicht als Beiwerk.',
    'ongdalsam.day.eyebrow': 'Ein Tag auf unserem Campus',
    'ongdalsam.day.title': 'Der Rhythmus eines Tages an der BDS',
    'ongdalsam.day.lead': 'Ein typischer Tag bewegt sich von stillen Anfängen in konzentrierte akademische Arbeit und wieder zurück in die Reflexion. Mahlzeiten, Bewegung und Stille sind Teil der Bildung, keine Unterbrechung.',
    'ongdalsam.day.t1_label': 'Morgenmeditation',
    'ongdalsam.day.t1_desc': 'Ein sanfter Start – Atem, Haltung und Konzentration, bevor der Tag beginnt.',
    'ongdalsam.day.t2_label': 'Frühstück',
    'ongdalsam.day.t2_desc': 'Frische, biologische Mahlzeiten im Tempelstil, gemeinsam im Speisesaal geteilt.',
    'ongdalsam.day.t3_label': 'Unterricht',
    'ongdalsam.day.t3_desc': 'Kleingruppenunterricht auf Englisch – Diskussion, Schreiben, Naturwissenschaften und Kunst.',
    'ongdalsam.day.t4_label': 'Mittagessen & Waldspaziergang',
    'ongdalsam.day.t4_desc': 'Eine Mittagspause – gutes Essen, frische Luft und Zeit weg vom Buch.',
    'ongdalsam.day.t5_label': 'Wahlfächer & Bewegung',
    'ongdalsam.day.t5_desc': 'Sport, Kunst, Kampfkunst und Talentprogramme nach Wahl der Lernenden.',
    'ongdalsam.day.t6_label': 'Lesen & Reflexion',
    'ongdalsam.day.t6_desc': 'Stille Zeit zum Lesen, Schreiben und Nachdenken vor dem Abend.',
    'ongdalsam.day.t7_label': 'Abendessen',
    'ongdalsam.day.t7_desc': 'Eine gemeinsame Mahlzeit in der Gemeinschaft – unaufgeregt und pflanzenbasiert.',
    'ongdalsam.day.t8_label': 'Abendstudium & Abschlussmeditation',
    'ongdalsam.day.t8_desc': 'Konzentriertes Lernen mit Mentorinnen und Mentoren, gefolgt von einer kurzen Meditation zum Tagesabschluss.',
    'ongdalsam.themes.eyebrow': 'Der Sieben-Tage-Rhythmus',
    'ongdalsam.themes.title': 'Ein Leitmotiv für jeden Wochentag',
    'ongdalsam.themes.lead': 'Jeder Wochentag trägt ein Leitmotiv – ein chinesisches Zeichen mit langer Bedeutungstradition. Zusammen bilden sie einen wöchentlichen Rhythmus aus Lernen, Bewegung, Stille und Gemeinschaft.',
    'ongdalsam.theme1.label': 'Aufrichtigkeit',
    'ongdalsam.theme1.desc': 'Ehrlich handeln',
    'ongdalsam.theme2.label': 'Stille',
    'ongdalsam.theme2.desc': 'Den Geist beruhigen',
    'ongdalsam.theme3.label': 'Bewegung',
    'ongdalsam.theme3.desc': 'Gesundes Handeln',
    'ongdalsam.theme4.label': 'Innehalten',
    'ongdalsam.theme4.desc': 'Stoppen und wahrnehmen',
    'ongdalsam.theme5.label': 'Betrachten',
    'ongdalsam.theme5.desc': 'Klar sehen',
    'ongdalsam.theme6.label': 'Harmonie',
    'ongdalsam.theme6.desc': 'Mit anderen leben',
    'ongdalsam.theme7.label': 'Klarheit',
    'ongdalsam.theme7.desc': 'Ein klarer, reiner Geist',
    'ongdalsam.facilities.eyebrow': 'Wo die Lernenden leben',
    'ongdalsam.facilities.title': 'Räume, die fürs Lernen gebaut sind',
    'ongdalsam.facilities.lead': 'Jeder Raum auf unserem Campus hat einen Sinn – den Körper zu erholen, ihn gut zu ernähren, den Geist zu sammeln und die Lernenden zusammenzuführen. Familien sind herzlich eingeladen, alles persönlich anzusehen.',
    'ongdalsam.facility1.title': 'Grünes Ondol-Haus',
    'ongdalsam.facility1.desc': 'Traditionelle Wohnräume mit warmem Bodenheizsystem – klein, sauber und für echten Ruheschlaf gestaltet. Die Lernenden schlafen in ruhigen, sicheren Zimmern, betreut vom Internatspersonal.',
    'ongdalsam.facility2.title': 'Haus des weißen Himmels',
    'ongdalsam.facility2.desc': 'Offene, lichtdurchflutete Wohnbereiche mit Blick in den Wald. Hier finden Lesen, kleine Gespräche und stille Erholung jeden Tag statt.',
    'ongdalsam.facility3.title': 'Speisesaal',
    'ongdalsam.facility3.desc': 'Mahlzeiten im Tempelstil – frisch, saisonal und überwiegend pflanzlich. Langsam und gemeinsam geteilt, sind sie Teil der täglichen Praxis.',
    'ongdalsam.facility4.title': 'Meditationshalle',
    'ongdalsam.facility4.desc': 'Eine stille Halle für die Morgenmeditation und die Abschlussübung am Abend. Hier lernen die Schülerinnen und Schüler, den Geist zu beruhigen.',
    'ongdalsam.facility5.title': 'Bibliothek & Lesesäle',
    'ongdalsam.facility5.desc': 'Eine Sammlung von Büchern in Englisch, Koreanisch und weiteren Sprachen. Ruhig, warm und mit langen Öffnungszeiten für Lesen und Recherche.',
    'ongdalsam.facility6.title': 'Waldwege & Außenbereiche',
    'ongdalsam.facility6.desc': 'Wanderwege, Übungsflächen im Freien und offene Plätze für Bewegung, Sport und saisonale Veranstaltungen.',
    'ongdalsam.gallery.eyebrow': 'Der Ort',
    'ongdalsam.gallery.title': 'Ein Blick auf unseren Campus',
    'ongdalsam.gallery.lead': 'Ein kleines Fenster in die Umgebung, in der die BDS-Lernenden ihre Tage verbringen. Familien sind jederzeit willkommen, sich alles persönlich anzusehen.',
    'ongdalsam.parents.eyebrow': 'Für Eltern',
    'ongdalsam.parents.title': 'Was Familien am meisten zählt',
    'ongdalsam.parents.lead': 'Ein Kind auf einen Internatscampus zu schicken ist eine bedeutende Entscheidung. Dies sind die Dinge, die wir für am wichtigsten halten – und an denen wir jeden Tag arbeiten.',
    'ongdalsam.parent1.title': 'Sicherheit und Fürsorge',
    'ongdalsam.parent1.desc': 'Internatsmitarbeitende leben auf dem Campus. Zimmer werden beaufsichtigt, die Gesundheit wird begleitet, und Familien werden über das Wohlergehen ihres Kindes informiert.',
    'ongdalsam.parent2.title': 'Gesunder Alltag',
    'ongdalsam.parent2.desc': 'Frische Bergluft, Mahlzeiten im Tempelstil, ausreichend Schlaf und ein ausgewogener Rhythmus aus Lernen, Bewegung und Ruhe.',
    'ongdalsam.parent3.title': 'Konzentriertes Lernen',
    'ongdalsam.parent3.desc': 'Ein Campus abseits städtischer Ablenkung, kleine Klassen und Mentorinnen und Mentoren, die jede Lernende und jeden Lernenden beim Namen kennen.',
    'ongdalsam.parent4.title': 'Offen für Familien',
    'ongdalsam.parent4.desc': 'Eltern sind eingeladen, uns zu besuchen, einen Tag auf dem Campus zu erleben und direkt mit Lehrkräften und Internatspersonal zu sprechen.',
    'ongdalsam.cta.title': 'Besuchen Sie unseren Campus vor Ort',
    'ongdalsam.cta.lead': 'Die BDS lässt sich am besten verstehen, wenn man im Wald steht, eine Mahlzeit teilt und einen Tag miterlebt. Wir laden Familien herzlich ein, uns zu besuchen.',
    'ongdalsam.cta.visit': 'Besuch vereinbaren',
    'ongdalsam.cta.contact': 'Zulassung kontaktieren'
  }
};
